packages/chain-adapters/package.json
packages/chain-adapters/src/api.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
yarn.lock

Add address validator package and add to eth adapter

Add eth address validator

---

packages/asset-service/package.json

asset-service version to 1.0.0

asset-service version to 1.0.0

---

packages/chain-adapters/src/api.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/chain-adapters/src/providers/UnchainedProvider.ts
packages/chain-adapters/src/types/BlockchainProvider.type.ts
packages/chain-adapters/src/types/PaginationParams.type.ts
packages/chain-adapters/src/types/Params.type.ts

- Rename PaginationParams to Params
- Add contract to getTxHistory params for filtering tx history by contract address.
closes #4

feat: add contract param to getTxHistory

---

.eslintrc
packages/asset-service/src/generateAssetData/generateAssetData.ts
packages/chain-adapters/src/api.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/market-service/src/coingecko/coingecko.ts

Update eth adapter to provide fee data.

update eth adapter

---

packages/market-service/src/api.ts
packages/market-service/src/coingecko/coingecko.test.ts
packages/market-service/src/coingecko/coingecko.ts
packages/market-service/src/index.ts

test: add market data service tests

---

packages/swapper/src/api.ts
packages/swapper/src/manager/SwapperManager.ts
packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
packages/swapper/src/swappers/zrx/ZrxSwapper.test.ts
packages/swapper/src/swappers/zrx/ZrxSwapper.ts
packages/swapper/src/swappers/zrx/getQuote/getQuote.test.ts
packages/swapper/src/swappers/zrx/getQuote/getQuote.ts

Add getAvailableAssets and canTradePair (renamed from validatePair) functions and tests
Remove undefined in getQuote return type as it was not needed and added more coverage

Zrx Available Assets

---

.github/workflows/pr.yml

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets

ci: add interim env var to avoid injection

---

packages/asset-service/package.json
packages/chain-adapters/package.json
packages/market-service/package.json
packages/swapper/package.json
packages/types/package.json

fixes this
https://github.com/shapeshift/lib/runs/3820210264
as per
https://github.com/lerna/lerna/issues/1821#issuecomment-510280765

ci: mark packages as public so they can be published

---

packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts

Dynamic btc fees from unchained

feat: dynamic btc fees

---

packages/chain-adapters/package.json
packages/swapper/package.json

needed to get web aligned on latest package versions

chore: bump and align package versions

---

packages/chain-adapters/package.json
packages/swapper/package.json

update chain adapters and types to latest

fix: update chain adapters and types to latest

---

packages/chain-adapters/package.json
packages/swapper/package.json

update to use latest chain adapter and types

fix: update to use latest chain adapter and types

---

packages/types/src/base.ts

chore: add comment to types

---

packages/types/src/base.ts

- Add comment to publish CI. My previous commits didn't include the proper syntax to publish a package ie `fix:`

fix: add comment to MaxAmountInput

---

packages/asset-service/package.json
packages/market-service/package.json
packages/swapper/package.json

- Bump package versions as a result of the previous publish

chore: bump lib versions

---

packages/chain-adapters/package.json
packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts

Unique id per account/scriptType to support subscribing to multiple sets of transactions by addresses

feat: create unique id for subscribe txs

---

packages/swapper/package.json
yarn.lock

check in missed yarn.lock update

chore: bump chain adapters package in swapper

---

packages/asset-service/package.json
packages/caip/package.json
packages/chain-adapters/package.json
packages/market-service/package.json
packages/swapper/package.json

fix: bump types

---

packages/asset-service/package.json
packages/market-service/package.json
packages/swapper/package.json

fix: update deps

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/types/src/chain-adapters/index.ts

send trade details over websocket from eth chain adapter

feat: send trade details over websocket from eth chain adapter

---

packages/chain-adapters/package.json
yarn.lock

update types used in chain adapters

fix: update types used in chain adapters

---

packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts

fix: remove unused `from` calculation

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts

fix: to address on erc20 sends

fix: to address on erc20 sends

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts

#313
- validateAddress tests
- validateEnsAddress tests 
- getAddress test

feat(EthereumChainAdapter): address methods tests

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts

#313
- add buildSendTransaction tests
- add broadcastTransaction tests

feat(EthereumChainAdapter): buildSendTransaction and broadcastTransaction tests

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts

#313
- add signTransaction tests to EthereumChainAdapter tests

feat(EthereumChainAdapter): add signTransaction tests

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts

#313
- add signAndBroadcastTransaction tests to EthereumChainAdapter tests

feat(EthereumChainAdapter): add signAndBroadcastTransaction tests

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts

#313
- buildSendTransaction: test throw on passed ENS 'to' in tx
- Immutably build `chainSpecific` mock with a `makeChainSpecific` builder which accepts an optional object of additional properties to be added to the base `chainSpecific` properties

feat(EthereumChainAdapter): test throw on passed ENS 'to'

---

packages/investor-yearn/README.md
packages/investor-yearn/package.json
yarn.lock

Fixes an issue in web where differing types of web3-eth-contract in node modules did not match, causing typescript issues.

feat: removed dev-dependency and made versioning of yearn sdk consistent

---

packages/investor-yearn/src/api/vaults.ts

adds the `expired` prop on yearn vaults

feat: expired prop on yearn vaults

---

.github/ISSUE_TEMPLATE/bounty.yml
.github/ISSUE_TEMPLATE/config.yml

finishing up from https://github.com/shapeshift/lib/pull/358

docs: bounty templates

---

package.json

Add `show-linked-packages` convenience script, like we have in `web`.

chore: add show-linked-packages script

---

packages/caip/src/adapters/yearn/utils.test.ts

Fix tests making network calls.

chore: mock yearn sdk in utils tests

---

packages/asset-service/src/service/AssetService.ts

Implementation for https://github.com/shapeshift/lib/issues/374
To summarize, the code provided in the issue description **greatly improves** the performance of the asset service, the gain is more than 2500 ms of execution time.
Some performance statistics :  (FCP is the value returned by reportWebVitals in the app)
- With legacy code : 
FCP = **6560 ms** on average for 5 executions
Function execution time = **2690 ms** on average for 5 executions
- With optimized code :
FCP = **4050ms** on average for 5 executions
Function execution time = **8 ms** on average for 5 executions
I saw no obvious other optimizations in the asset service, notably flattenAssetData function is not costly.

feat: improve asset service performance

---

packages/asset-service/package.json
packages/caip/package.json
packages/chain-adapters/package.json
packages/investor-yearn/package.json
packages/market-service/package.json
packages/swapper/package.json

Bump package versions that have new releases

chore: bump package version

---

packages/market-service/package.json
packages/market-service/src/coincap/coincap.ts
packages/market-service/src/coingecko/coingecko.ts
packages/market-service/src/config.ts
packages/market-service/src/utils/rateLimit.ts
packages/market-service/src/utils/rateLimiters.test.ts
packages/market-service/src/utils/rateLimiters.ts
packages/market-service/src/yearn/yearn-tokens.test.ts
packages/market-service/src/yearn/yearn-tokens.ts
packages/market-service/src/yearn/yearn-vaults.test.ts
packages/market-service/src/yearn/yearn-vaults.ts
yarn.lock

Rate limiter implemented for market-service package + unit tests
closes #367

feat: market service rate limiter

---

jest.config.ts
packages/caip/src/adapters/coincap/index.test.ts
packages/caip/src/adapters/coincap/utils.ts
packages/caip/src/adapters/coingecko/index.test.ts
packages/caip/src/adapters/coingecko/utils.ts
packages/caip/src/caip19/caip19.test.ts
packages/caip/src/caip19/caip19.ts
packages/caip/src/caip2/caip2.test.ts
packages/caip/src/caip2/caip2.ts
packages/types/src/base.ts

Osmosis needs it own ChainType but the caip namespace is `cosmos`

fix: caip support for Osmosis

---

packages/chain-adapters/package.json
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/types/src/chain-adapters/index.ts
yarn.lock

**Description**
Add metadata to transaction WebSocket messages to propagate the addition of metadata in https://github.com/shapeshift/unchained/pull/278.

feat: add metadata to transaction WebSocket messages

---

packages/types/src/chain-adapters/index.ts

**Description**
Adds `TxType.Contract`, in support of current tx parsing work.
**Context**
Supports https://github.com/shapeshift/web/issues/1068

feat: add "Contract" TxType

---

packages/chain-adapters/package.json
packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts

Baseline cosmos parser for implementation of `getTxHistory` and `subscribeTxs`

chore: cosmos parser

---

packages/market-service/src/osmosis/osmosis.ts

- Fix osmosis market service chart api call

fix: fix osmosis charts

---

package.json
yarn.lock

* Upgrade TypeScript to 4.6.2
* Upgrade eslint to be compatible with TypeScript 4.6

chore: upgrade TypeScript to 4.6.2

---

packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts

fix: btc getAddress uses the wrong accountType

---

packages/market-service/src/foxy/foxy.test.ts
packages/market-service/src/foxy/foxy.ts
packages/market-service/src/foxy/foxyMockData.ts
packages/market-service/src/market-providers.ts
packages/market-service/src/market-service.test.ts
packages/market-service/src/marketDataCLI.ts

- Add foxy market data service

add foxy market service

---

packages/chain-adapters/package.json
yarn.lock

Update @shapeshiftoss/unchained-client to v6.2.0

chore: update unchained-client to v6.2.0

---

packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts

- Add error handling to `buildSendTransaction`

chore: add error handling

---

packages/chain-adapters/package.json
packages/chain-adapters/src/ChainAdapterManager.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
yarn.lock

update unchained client version and use parsedTx instead of SequencedTx.
Needed for latest changes in unchained client parser

chore: update unchained client version

---

packages/chain-adapters/package.json
yarn.lock

bump unchained client for parser fix

chore: bump unchained client for parser fix

---

packages/chain-adapters/src/ChainAdapterCLI.ts
packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
packages/types/src/chain-adapters/index.ts

Delegate, Undelegate and Withdraw transactions.
TODO later: dry up the chain adapter

feat: delegate, undelegate and withdraw transactions

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/types/src/chain-adapters/ethereum.ts

Intended to supersede #439. Required for https://github.com/shapeshift/web/issues/1181. Fixes #441. Relevant to https://github.com/shapeshift/web/issues/1025.

feat: support eip-1159 in buildSendTransaction

---

packages/investor-foxy/src/api/api.ts

fix: use mostly right rebase history if one fails

---

packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts

revert(chain-adapters): "fix: cosmos-sdk/MsgWithdrawDelegationReward"

---

packages/asset-service/src/generateAssetData/baseAssets.ts
packages/asset-service/src/generateAssetData/cosmos/getOsmosisAssets.ts
packages/asset-service/src/generateAssetData/ethTokens/ethereum.ts
packages/asset-service/src/generateAssetData/ethTokens/foxy.ts
packages/asset-service/src/generateAssetData/ethTokens/overrides.ts
packages/asset-service/src/generateAssetData/ethTokens/uniswap.ts
packages/asset-service/src/generateAssetData/ethTokens/yearnVaults.ts
packages/asset-service/src/generateAssetData/utils.test.ts
packages/asset-service/src/generateAssetData/utils.ts
packages/asset-service/src/service/AssetService.test.ts
packages/asset-service/src/service/AssetService.ts
packages/asset-service/src/service/AssetServiceTestData.ts
packages/swapper/src/swappers/zrx/ZrxBuildQuoteTx/ZrxBuildQuoteTx.test.ts
packages/swapper/src/swappers/zrx/ZrxSwapper.test.ts
packages/swapper/src/swappers/zrx/utils/test-data/assets.ts
packages/types/src/base.ts

One of two PRs required to close #570

feat: add assetid, chainid fields to asset type

---

packages/swapper/src/swappers/zrx/ZrxBuildQuoteTx/ZrxBuildQuoteTx.test.ts
packages/swapper/src/swappers/zrx/ZrxBuildQuoteTx/ZrxBuildQuoteTx.ts
packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.test.ts
packages/swapper/src/swappers/zrx/getZrxQuote/getZrxQuote.test.ts
packages/swapper/src/swappers/zrx/getZrxQuote/getZrxQuote.ts
packages/types/src/base.ts

None of this is being used.
I tested these removals locally linked to web and it looks fine

chore: remove unused values from swapper types

---

.eslintrc
packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
packages/investor-foxy/src/foxycli.ts

Add `object-shorthand` lint rule, and fix non-complying occurrences.
N/A
N/A
N/A
N/A

chore: add object-shorthand ESLint rule

---

packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
tsconfig.build.json

Add `noUnusedParameters` TS rule.
N/A
N/A
N/A
N/A

chore: add noUnusedParameters TS rule

---

packages/asset-service/package.json
packages/caip/package.json
packages/chain-adapters/package.json
packages/investor-foxy/package.json
packages/investor-yearn/package.json
packages/market-service/package.json
packages/swapper/package.json
packages/unchained-client/CHANGELOG.md
packages/unchained-client/README.md
packages/unchained-client/package.json

chore: manually set changelog version and package version for proper publish

---

packages/caip/README.md
packages/caip/package.json

BREAKING CHANGE: properly bump major version

perf(caip): bump caip version

---

packages/swapper/src/swappers/zrx/ZrxSwapper.ts

Fixes: https://github.com/shapeshift/web/issues/1746

fix: dont crash when passing undefined to filterBuyAssetsBySellAssetId

---

packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.ts

somehow this made it in and broke swapping

fix: swapper mixup

---

packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.ts
packages/swapper/src/swappers/zrx/utils/helpers/helpers.test.ts
packages/swapper/src/swappers/zrx/utils/helpers/helpers.ts
packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts

chore: tighten up normalizeamount

---

packages/asset-service/src/generateAssetData/baseAssets.ts
packages/asset-service/src/generateAssetData/cosmos/getOsmosisAssets.ts
packages/asset-service/src/service/generatedAssetData.json
packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
packages/unchained-client/src/cosmos/parser/index.ts
yarn.lock

- Regenerate assets with correct osmosis explorer link and chain type.
- pass optional assetID to cosmos parser so it can set itself as osmosis

fix: fix osmosis assets & parsing

---

packages/swapper/src/swappers/test/TestSwapper.ts

use mainnet btc for test swapper

fix: use mainnet btc for test swapper

---

packages/caip/src/adapters/thortrading/index.test.ts
packages/caip/src/adapters/thortrading/index.ts
packages/caip/src/assetId/assetId.ts

- Add `poolAssetIdToAssetId` and `assetIdToPoolAssetId` helper functions to convert midgard pool asset Ids to caip 19 asset ids.
- This will be used for interacting with midgard api for thorchain swapper implementation.
closes #700

feat: thorchain caip adapter

---

packages/swapper/src/api.ts
packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts

thor trade types for eth or btc tx data

feat: thor trade types for eth or btc tx data

---

packages/market-service/src/coingecko/coingecko.ts

we we're getting rate limited by coingecko - add support for using the coingecko pro url and
injecting the api key if we have one

feat: support coingecko pro with api key

---

packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
packages/unchained-client/src/ethereum/parser/__tests__/ethereum.test.ts
packages/unchained-client/src/ethereum/parser/erc20Approve.ts
packages/unchained-client/src/ethereum/parser/index.ts
packages/unchained-client/src/ethereum/types.ts
packages/unchained-client/src/types.ts

Added subparser for ERC20 approve method
Closes https://github.com/shapeshift/lib/issues/658

feat: generic erc20 approve

---

package.json
packages/asset-service/package.json
packages/caip/package.json
packages/chain-adapters/package.json
packages/errors/package.json
packages/investor-foxy/package.json
packages/investor-yearn/package.json
packages/investor/package.json
packages/market-service/package.json
packages/swapper/package.json
packages/types/package.json
packages/unchained-client/package.json
yarn.lock

chore: update @shapeshiftoss dependencies
Also synchronize some other deps to all reference the same version

chore: update @shapeshiftoss dependencies

---

packages/asset-service/package.json
packages/asset-service/src/generateAssetData/baseAssets.ts
packages/asset-service/src/generateAssetData/cosmos/getOsmosisAssets.ts
packages/asset-service/src/generateAssetData/ethTokens/foxy.ts
packages/asset-service/src/generateAssetData/ethTokens/overrides.ts
packages/asset-service/src/generateAssetData/ethTokens/uniswap.ts
packages/asset-service/src/generateAssetData/ethTokens/uniswapV2Pools.ts
packages/asset-service/src/generateAssetData/ethTokens/yearnVaults.ts
packages/asset-service/src/service/AssetService.test.ts
packages/asset-service/src/service/AssetServiceTestData.ts
yarn.lock

BREAKING CHANGE: Asset shape has changed

feat(asset-service): remove "chain" and "network" from assets

---

packages/investor-foxy/package.json
packages/investor-foxy/src/api/api.ts
packages/investor-foxy/src/foxycli.ts
packages/investor-yearn/README.md
packages/investor-yearn/package.json
packages/investor-yearn/src/YearnInvestor.ts
packages/investor-yearn/src/YearnOpportunity.ts
packages/investor-yearn/src/yearncli.ts
yarn.lock

feat(investor-foxy): use "KnownChainIds" instead of "ChainTypes"
BREAKING CHANGE: Requires updated peerDependencies

feat(investor-yearn): use "KnownChainIds" instead of "ChainTypes"

---

packages/chain-adapters/src/ChainAdapterCLI.ts

refactor(chain-adapters): fix adapter url in cli

---

packages/chain-adapters/src/ChainAdapterCLI.ts

refactor(chain-adapters): fix btc cli example

---

packages/swapper/src/manager/SwapperManager.test.ts
packages/swapper/src/swappers/thorchain/ThorchainSwapper.test.ts
packages/swapper/src/swappers/thorchain/types.ts
packages/swapper/src/swappers/thorchain/utils/estimateTradeFee/estimateTradeFee.test.ts
packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.test.ts
packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.test.ts
packages/swapper/src/swappers/thorchain/utils/getUsdRate/getUsdRate.test.ts

- We need web3 for erc20 approval calls for thorchain trading.

feat: add web3 to thorchain swapper deps

---

packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
packages/chain-adapters/src/bitcoin/types.ts
packages/chain-adapters/src/types.ts

move op return into chainSpecific for getFees

fix: move op return data into chain specific for get fees

---

packages/swapper/package.json
packages/swapper/src/swappers/thorchain/utils/txFeeHelpers/btcTxFees/getBtcTxFees.ts

add function to return quote fee data for btc trades

feat: btc thor trade fees

---

packages/swapper/src/swappers/thorchain/utils/ethereum/makeTradeTx.ts

makeTradeTx now takes: gasPrice OR (maxFeePerGas and maxPriorityFeePerGas)

feat: maketrade work with either gasprice or eip1559

---

packages/swapper/src/api.ts

This was most likely changed accidentally. fixes it back

fix: swapper tradetxs type

---

packages/swapper/src/swappers/thorchain/utils/txFeeHelpers/ethTxFees/getEthTxFees.ts

fallback on known good gas limit if estimate fails

chore: fallback on known good gas limit if estimate fails

---

packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts

make getpublickey public so we can use it with thor trading

chore: make getpublickey public so we can use it with thor trading

---

packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
packages/swapper/src/swappers/osmosis/utils/helpers.ts

fix filtering by assets in osmosis
didn't realize this function changed

fix(swapper): filtering by assets

---

packages/investor-foxy/src/api/foxy-types.ts

dummy comment in affected files to force semantic release to publish this package

chore: publish investor-foxy

---

packages/asset-service/package.json
packages/caip/package.json
packages/chain-adapters/package.json
packages/investor-foxy/package.json
packages/investor-yearn/package.json
packages/market-service/package.json
packages/swapper/package.json
packages/unchained-client/package.json

This bootstraps the lib packages following https://github.com/shapeshift/lib/pull/893

fix: unrug lib bump packages

---

packages/swapper/src/api.ts
packages/swapper/src/swappercli.ts
packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
packages/swapper/src/swappers/utils/test-data/setupSwapQuote.ts
packages/swapper/src/swappers/zrx/utils/test-data/setupZrxSwapQuote.ts
packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.test.ts
packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts

remove buy asset account number. 
corrsponding web pr:
https://github.com/shapeshift/web/pull/2258

chore: remove buy asset account number

---

packages/swapper/src/swappers/thorchain/utils/constants.ts
packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.test.ts
packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.ts

affiliate fee support. hardcoded to 0 for now.
To test:
1) set THORCHAIN_AFFILIATE_BIPS
2) link to web locally & build
3) perform a thor swap and see our affiliate balance increase:
https://thornode.thorswap.net/thorchain/thorname/ss
https://viewblock.io/thorchain/address/thor1kue5wlk5nkf8l7c5vg5cj5r7dmc0zyfmst4rqs

chore: add affiliate fee to memo

---

packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
packages/swapper/src/swappers/cow/utils/constants.ts
packages/swapper/src/swappers/cow/utils/helpers/helpers.test.ts

Uses the CowSwap-provided appdata to identify the trades we execute from the ShapeShift app
- contributes to https://github.com/shapeshift/web/issues/2364 - to be closed with a web packages bump PR

feat(swapper): cowswap app data

---

packages/investor-foxy/src/api/api.ts
packages/investor-idle/src/IdleOpportunity.ts
packages/investor-idle/src/idlecli.ts
packages/investor-yearn/src/YearnOpportunity.ts
packages/investor-yearn/src/yearncli.ts

A refactor to use only use `bnOrZero` when we actually need it.
N/A
Minimal.
CI should pass.
N/A

refactor: tidy usage of `bnOrZero`

---

packages/asset-service/src/generateAssetData/ethereum/uniswapV2Pools.ts
packages/asset-service/src/service/generatedAssetData.json

naming update as directed by @reallybeard

chore: update asset definition for fox weth univ2 lp token

---

packages/chain-adapters/src/api.ts
packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
packages/chain-adapters/src/evm/EvmBaseAdapter.ts
packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
packages/chain-adapters/src/types.ts
packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.test.ts
packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.test.ts
packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.test.ts
packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.test.ts

required to get non-zero `accountNumbers` for multi account in web

feat: add getBIP44Params to IChainAdapter and impl

---

packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts

- also fixes send max logic for cosmossdk coins

fix: handle thorchain black magic fees correctly

---

packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
packages/chain-adapters/src/cosmossdk/thorchain/types.ts
packages/chain-adapters/src/evm/EvmBaseAdapter.ts
packages/swapper/sample.env
packages/swapper/src/adapters.ts
packages/swapper/src/api.ts
packages/swapper/src/swappercli.ts
packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
packages/swapper/src/swappers/thorchain/buildThorTrade/buildThorTrade.ts
packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
packages/swapper/src/swappers/thorchain/utils/cosmos/cosmosTxData.ts
packages/swapper/src/swappers/thorchain/utils/estimateTradeFee/estimateTradeFee.ts
packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.test.ts
packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.ts
packages/swapper/src/swappers/thorchain/utils/getUsdRate/getUsdRate.test.ts
packages/swapper/src/swappers/thorchain/utils/getUsdRate/getUsdRate.ts
packages/swapper/src/swappers/thorchain/utils/isRune/isRune.ts
packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.ts

Adds support for swapping to/from RUNE, the native asset of Thorchain. Also supporting Thorchain synth assets would be a small stretch.

feat: swap to/from RUNE

---

packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.ts

fix: get price ratio when buy asset is rune

---

packages/caip/src/adapters/mtpelerin/index.ts

Adds support to Mt Pelerin for additional assets.
closes #1047

fix: add support for EUROC, LUSD, XCHF

---

packages/investor/package.json
packages/investor/src/InvestorOpportunity.ts

This PR is at the top of the dependency tree. Merge me first 😃 
Contributes to https://github.com/shapeshift/lib/issues/999.

feat(investor): enforce `bip44Params` on `signAndBroadcast`

---

packages/investor-idle/src/IdleOpportunity.ts

Adds a new `getRewardAssetIds` method to `investor-idle` opportunities, to get the rewards AssetIds an Idle opportunity yields.
- link in web
- Console.log/debug that method call wherever we have access to an opportunity e.g  here https://github.com/shapeshift/web/blob/43d8a9b3e0660f5f622b33425c3e7cd8752d3254/src/pages/Defi/hooks/useVaultBalances.tsx#L79
- Ensure we get a tuple of 1, 2 or 3 `AssetId`s depending on the opportunity

feat(investor-idle): getRewardAssetIds

---

packages/swapper/src/swappers/osmosis/utils/helpers.ts
packages/swapper/src/swappers/osmosis/utils/types.ts

pools api has changed from camelCase to snake_case
fixes issues loading quotes for osmo / atom trades

fix: osmosis api pools api has changed

---

packages/swapper/src/swappers/osmosis/utils/helpers.ts

use correct chain for osmo trades. fixes keplr

fix(swapper): use correct chain for osmo trades. fixes keplr

---

packages/market-service/src/idle/idleMockData.ts
packages/market-service/src/market-service.test.ts

fixes tests for new market service added in https://github.com/shapeshift/lib/pull/1097
turned on extra branch protection for `main` - all PRs must be up to date to prevent this occurring again

test: fix market service tests

---

packages/swapper/src/swappers/test/TestSwapper.test.ts

chore: remove TestSwapper test

---

packages/swapper/package.json

feat(swapper): bump @shapeshiftoss/chain-adapters to latest

---

packages/swapper/src/swappers/thorchain/utils/evm/utils/getThorTxData.ts

Use the sell `AssetId` in `getInboundAddressDataForChain`.

fix(swapper): use sell AssetId in getInboundAddressDataForChain

---

packages/caip/src/adapters/thortrading/index.ts

Add the missing BNB pool ID entry for BNB.BNB

feat(caip): add bnb to thorPoolIdAssetIdSymbolMap

---

packages/swapper/src/swappers/osmosis/utils/helpers.ts

Cache osmo pools data because its called a LOT

fix(swapper): cache osmo pools endpoint

---

packages/types/src/index.ts
packages/types/src/utility.ts

Exports all utility types for use in web -`UnionMerge` consumed in https://github.com/shapeshift/web/pull/3598

feat(types): export all utility types

---

packages/swapper/src/swappers/osmosis/utils/helpers.ts

changing pagination to 10 broke things. changes it back to 1000.

fix: changing pagination to 10 broke things. changes it back to 1000

---

packages/caip/package.json
packages/caip/src/adapters/mtpelerin/index.ts
packages/caip/src/adapters/onramper/index.ts

Add supported optimism assets for the fiat ramps

feat: add optimism assets

---

packages/asset-service/src/generateAssetData/osmosis/index.ts
packages/asset-service/src/service/generatedAssetData.json

* use `rawcdn.githack.com` + latest commit hash in github static data requests to avoid rate limiting and ensure data freshness

fix(asset-service): use recommended githack url format for osmosis urls

---

packages/caip/src/utils.test.ts
packages/caip/src/utils.ts

* adds handler to generatAssetIdFromOsmosisDenom for LP tokens
* adds tests for generateAssetIdFromOsmosisDenom

feat(caip): generate asset ids from osmosis lp token denoms

---

packages/asset-service/src/service/generatedAssetData.json

Bertha because of the Osmo head change upstream, but this is actually only adding `Morpho` and `Euler` tranches Idle assets. Run `git diff origin/main` locally with these two strings and ensure we're 🥯 here

feat(asset-service): regenerate asset data

---

packages/swapper/src/swappers/index.ts

Export `isRune` for consumption in `web`.

chore(swapper): export isRune

---

packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
packages/chain-adapters/src/cosmossdk/types.ts

* adds support for sending osmosis network tokens to OsmosisChainAdapter

feat(chain-adapters): add osmosis token send support

---

packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.test.ts
packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.ts

Extract the non-fee parts from https://github.com/shapeshift/lib/pull/1187

fix: magic strings and mutation are bad

---

packages/caip/src/adapters/osmosis/index.ts
packages/caip/src/adapters/osmosis/utils.ts

* adds a caip adapter to convert Osmosis LP AssetIds to Osmosis pool ids

feat(caip): add osmosis lp asset id to pool id adapter

---

packages/chain-adapters/package.json
packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
packages/investor-foxy/package.json
packages/investor-idle/package.json
packages/investor-yearn/package.json
packages/investor/package.json
packages/swapper/package.json
packages/swapper/src/swappers/osmosis/utils/helpers.ts
yarn.lock

* use consistent case style for all fields in osmosis transactions
* depends on https://github.com/shapeshift/proto-tx-builder/pull/17
* depends on https://github.com/shapeshift/hdwallet/pull/534

fix(chain-adapters): use snake_case for all osmosis tx fields

---

packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts

JS pls
Required for https://github.com/shapeshift/web/pull/3901

fix(swapper): osmosis account 0 receiveAccountNumber

---

packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
packages/chain-adapters/src/types.ts

* fixes incorrectly-named field in osmosis lp remove transaction

fix(chain-adapters): field name in osmosis lp remove transaction

---

packages/investor-foxy/src/api/api.ts
packages/investor-foxy/src/constants/enums.ts

feat(investor-foxy): rename Token_Staking provider to Staking

---

packages/asset-service/src/index.ts

required for https://github.com/shapeshift/web/pull/4102

feat: expose getRenderedIdenticonBase64 from asset service
