shapeshift/lib

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/workflows/release.yml
- .releaserc.json
- package.json
This PR does a few things but gets us much closer to CI being setup for this repo.
- **Lints the PR title, rather than every commit.** This is what we actually originally wanted. The PR will get squashed into `main`, and the title will be the commit message. The PR title will be used to for the changelog, and to determine what type of release to do off of `main`, and allows people to make whatever commits they want to their branch before PRing.
- **Runs the `commitlint` step on the `release` action on `main`** - in the event that we sneak in a PR title that doesn't confirm CI will fail.
- Adds a PR template with docs describing how to title PRs correctly.
- Will run a `Release` step on pushing (merging) to `main`. This uses `semantic-release` and a bunch of plugins to do the following
- …
> ci: add semantic release

- commitlint.config.js
commitlint was too aggressive and won't accept dependabot PR titles like `chore(deps): bump semver-regex from 3.1.2 to 3.1.3`
this changes the rule to ignore the scope, e.g. the `(deps)` in `chore(deps): ...` to make ci great again
> ci: commitlint config for dependabot

- .eslintignore
- README.md
- package.json
- scripts/linkPackages.js
scripts to `yarn link` or `yarn unlink` all packages as new devs have had issues with this
> chore: yarn link scripts and docs

- packages/asset-service/src/service/AssetService.test.ts
- packages/asset-service/src/service/AssetService.ts
- packages/chain-adapters/src/ChainAdapterCLI.ts
- packages/chain-adapters/src/bip32.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/market-service/src/coingecko/coingecko.test.ts
- packages/market-service/src/coingecko/coingecko.ts
- packages/market-service/src/index.ts
- packages/swapper/src/manager/SwapperManager.ts
- packages/swapper/src/swappers/zrx/executeQuote/executeQuote.ts
- packages/swapper/src/swappers/zrx/utils/constants.ts
- packages/types/src/base.ts
- packages/types/src/chain-adapters/bitcoin.ts
- packages/types/src/chain-adapters/ethereum.ts
- packages/types/src/chain-adapters/index.assert.ts
- packages/types/src/chain-adapters/index.ts
* make asset service throw if description not found
* make asset service `byTokenId` throw if not found
* removed unused params from bip32 `toRootDerivationPath`
* various lint fixes
* skip failing or unimplemented tests in btc chain adapters
* use `0x` for callData in eth chain adapters if no contract address provided
* fix bip32 utils and tests
* export missing type from chainadapters
> fix: various tweaks

- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
get btc sends working by allowing optional to+value to be used instead of recipients.
Allows it to be called in the same way as the eth chain adapter buildSendTransaction()
> fix: get btc sends working by allowing optional to+value to be used instead of recipients

- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/utils/utxoUtils.ts
- we only need to calculate the change address type once
- turns out we don't even need to specify `scriptType` on `BTCOutputAddressType.Spend` outputs!
> refactor: simplify #177 a bit

- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/types/src/chain-adapters/index.ts
This is needed for the Receive screen to allow the user to manually verify the address from the device
> feat: enable getAddress to show on device

- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
This fixes Eth sends not working for KeepKey.
They work for native because native does the conversion inside `ethSignTx` but converting it here will still be fine (I tested it)
> fix: eth nonce is expected to be hex in hdwallet

- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/types/src/chain-adapters/bitcoin.ts
- packages/types/src/chain-adapters/index.ts
- remove fees returning from buildSendTx
- remove recipients from buildSendTx
- add btc specific fee data and stub out return values
https://github.com/shapeshift/web/issues/215
We need to show fees on frontend and let them be selectable (it's all showing 0 right now) but the way we were expecting to do fees in frontend code was only applicable to eth and not the greatest (getting the fees from calling buildSendTx instead of getFees).
I will have a few additional changes to lib in upcoming prs but wanted to break it into smaller pieces.
> fix: fees part 1 cleanup

- packages/chain-adapters/package.json
- packages/chain-adapters/src/ChainAdapterCLI.ts
- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/swapper/src/swappers/zrx/executeQuote/executeQuote.ts
- packages/swapper/src/swappers/zrx/utils/helpers/helpers.ts
- packages/types/src/chain-adapters/bitcoin.ts
- packages/types/src/chain-adapters/ethereum.ts
- packages/types/src/chain-adapters/index.ts
- Make buildSendTxInput generic with different eth and btc chainSpecific fields
- Pass satoshiPerByte into btc buildSendTx instead of deriving in it (so there is never a difference between what user is told vs what fee it sends with)
- make gas fee and gasLimit required for eth instead of calling getFeeData in buildSendTx
This moves us further towards doing fees correctly: https://github.com/shapeshift/web/issues/215
> feat: chain specific buildtx

- packages/types/src/base.ts
- Add types needed for max trade PR for [web](https://github.com/shapeshift/web/pull/316/files) and [lib](https://github.com/shapeshift/lib/pull/200/files)
> feat: add SendMaxAmountInput to base types

- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
pass through optional param to verify btc address on device
> fix: pass through optional param to verify btc address on device

- packages/asset-service/package.json
- packages/caip/package.json
- packages/chain-adapters/package.json
- packages/market-service/package.json
- packages/swapper/package.json
- packages/swapper/src/api.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.test.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- packages/swapper/src/swappers/zrx/approvalNeeded/approvalNeeded.test.ts
- packages/swapper/src/swappers/zrx/approveInfinite/approveInfinite.ts
- packages/swapper/src/swappers/zrx/getSendMaxAmount/getSendMaxAmount.test.ts
- packages/swapper/src/swappers/zrx/getSendMaxAmount/getSendMaxAmount.ts
- packages/swapper/src/swappers/zrx/utils/bignumber.ts
- packages/swapper/src/swappers/zrx/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/zrx/utils/helpers/helpers.ts
- packages/swapper/src/swappers/zrx/utils/test-data/setupZrxDeps.ts
- Add `getSendMaxAmount` helper function to ZrxSwapper. This gives us the ability to get the max amount a eth address can swap.
closes #167
> feat: add getSendMaxAmount to swapper

- packages/caip/src/caip19/caip19.ts
- packages/caip/src/caip2/caip2.ts
- packages/caip/src/index.ts
let's use use `CAIP2` or `CAIP19` as a type in web, which are just strings, but makes the types much more descriptive
> feat: export CAIP2 and CAIP19 as string alias

- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/types/src/chain-adapters/ethereum.ts
- Fee data was incorrect for erc20.
- got rid of 2x padding ridiculousness because fees are now correct
- Add optional contractData field to be used as a generic way for other parts of the app to get fee data (zrxSwapper)
> fix: gas fees erc20

- packages/swapper/src/swappers/zrx/getSendMaxAmount/getSendMaxAmount.test.ts
- packages/swapper/src/swappers/zrx/getSendMaxAmount/getSendMaxAmount.ts
- This updates the way `getSendMaxAmount` passes arguments to `getFeeData` based on the changes made in this [PR](https://github.com/shapeshift/lib/pull/223/files)
- closes #226
> fix: update getSendMaxAmount to pass quote txData to getFeeData

- packages/chain-adapters/package.json
- packages/chain-adapters/src/ChainAdapterCLI.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/utils/utxoUtils.test.ts
- packages/chain-adapters/src/utils/utxoUtils.ts
- packages/types/src/chain-adapters/bitcoin.ts
- packages/types/src/chain-adapters/index.ts
- yarn.lock
* [MAJOR] fix: replace references to "scriptType" with "accountType"
* feat: add "convertXpubVersion" function to convert any public key to an x-, y-, or z-pub
The purpose of this change is that `scriptType` can be assumed based on the `accountType`, but not the other way around. We should be passing around the `accountType` and then deriving the `scriptType` to use from that.
This fixes portis BTC balances not working because 
1. Portis always returns its public key in "xpub" format, even for Segwit public keys.
2. Blockbook generates addresses from a public key by INFERRING the account type from the public key prefix of `"xpub" | "ypub" | "zpub"`.
3. We now convert every public key we get into an `"xpub" | "ypub" | "zpub"` based on the `accountType` that's provided
> fix: portis wallet not showing BTC balance

- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- packages/swapper/src/swappers/zrx/getSendMaxAmount/getSendMaxAmount.test.ts
- packages/swapper/src/swappers/zrx/getSendMaxAmount/getSendMaxAmount.ts
- packages/swapper/src/swappers/zrx/utils/constants.ts
- Pads the estimated gas fee for max ETH trades. 
- Changes default trading to ETH/FOX
closes #239
> fix: fix send max for eth bug

- packages/swapper/package.json
- yarn.lock
Locked web3 version is blocking https://github.com/shapeshift/web/pull/475 downstream; this unlocks the version and bumps it to 1.6.1 to match that PR, just for good measure. In the future, `yarn-minify` will keep versions in sync.
> chore: unlock/bump web3

- packages/caip/src/adapters/coingecko/index.ts
This is, as far as I can tell, the biggest culprit in the Case of the Slow Page Load; the object allocation is high-overhead by itself, but the spread operator also gets transpiled down to use a babel shim that allocates extra temporary arrays of the intermediate objects' properties and loops over them.
> fix: speed up invert of generated caip info

- packages/asset-service/package.json
- packages/caip/package.json
- packages/chain-adapters/package.json
- packages/market-service/package.json
- packages/swapper/package.json
- packages/types/package.json
- yarn.lock
This should fix versioning issues when a lib package requires another lib package that the parent project also requires.
Basically, when we upgrade a version of a package in `web` (the parent project), and a `lib` dependencies has a direct dependency on another `lib` package, `yarn` will install the newer package at (for example) `node_modules/@shapeshiftoss/chain-adapters` but will install a second copy under (for example) `node_modules/@shapeshiftoss/swapper/node_modules/@shapeshiftoss/chain-adapters`.
This leads to 2 copies of the same package, even if the semver requirements match. `yarn` will not hoist the second package to the root `node_modules`.
`peerDependencies` means that the package excepts the parent project to have already imported that dependency and that this package will …
> feat: use sibling packages as peerDependencies

- packages/caip/src/caip19/caip19.ts
- packages/caip/src/caip2/caip2.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/OsmosisChainAdapter.ts
Add support for cosmos and osmosis caip2 & caip19
We still need to figure out support for ibc assets on those chains but this gets us started with the base assets
> add caip2 and caip19 support for cosmos & osmosis

- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
This adds `chain-adapters` support for ENS address in address validation.
> feat: add ENS validation

- packages/chain-adapters/src/api.ts
This adds a `ChainSpecificAdapterProps<T, U, V>` type as proposed by @reidrankin in shapeshift/web#704 and extends ChainAdapter with a single usage of it, for ChainTypes.Ethereum.
`ChainSpecificAdapterProps` is to be used as an intersection with ChainAdapter and allows to declare chain-specific properties for each chain.
Example usage: https://github.com/shapeshift/web/blob/65ea158bdba3623842eec4cb919bf3f650ae5bd7/src/components/Modals/Send/views/Address.tsx#L83
> feat: improve ChainAdapter typings

- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
This was spotted while writing `EthereumChainAdapter` tests in #313.
When building a send tx and using the `sendMax` option, we currently throw on no ERC20 balance, but we don't in case of no native token balance.
> feat(buildSendTransaction): throw on sendMax with 0 balance

- packages/chain-adapters/src/ChainAdapterManager.test.ts
- packages/chain-adapters/src/ChainAdapterManager.ts
This is a step toward not using the ChainTypes enum by using a CAIP2 string to get the ChainAdapter instance.
`byChainId` takes a `CAIP2` value and returns a ChainAdapter instance or throws an error.
This PR is not associated with an existing issue.
> feat: add "byChainId" function to ChainAdapter Manager

- packages/asset-service/src/service/AssetService.test.ts
- packages/asset-service/src/service/AssetService.ts
- packages/chain-adapters/package.json
- packages/market-service/package.json
- packages/types/src/base.ts
Add `isTrusted` boolean to asset service description function in order to determine the trusted (hard coded in the `descriptions.json` file) and non trusted (3rd party) descriptions.
> feat: add isTrusted to description of asset service

- packages/swapper/src/swappers/zrx/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/zrx/utils/helpers/helpers.ts
Fix for https://github.com/shapeshift/web/issues/568
The rate fetched from 0x api for $1 is imprecise for multiple assets, in practice we notice a more precise rate by fetching rate for $100 / $1000 value.
> fix: incorrect usd rate for multiple assets

- packages/asset-service/package.json
- packages/caip/package.json
- packages/chain-adapters/package.json
- packages/market-service/package.json
- packages/swapper/package.json
- yarn.lock
chore: upgrade axios to 0.26.0
This is just to keep up on dependencies, especially those that may included security fixes
> chore: upgrade axios to 0.26.0

- packages/chain-adapters/src/ChainAdapterManager.test.ts
- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- In `api.ts`, change `getCaip2()` to be synchronous and add `getChainId()`
```ts
import { caip2 } from '@shapeshiftoss/caip'
export class ChainAdapter implements IChainAdapter<ChainTypes.Ethereum> {
private readonly chainId = 'bip122:000000000019d6689c085ae165831e93'
constructor(args: ChainAdapterArgs) {
if (args.chainId) {
try {
const { chain } = caip2.fromCAIP2(args.chainId)
if (chain !== ChainTypes.Bitcoin) {
throw new Error()
}
this.chainId = args.chainId
} catch (e) {
throw new Error(`The ChainID ${args.chainId} is not supported`)
} 
}
this.providers = args.providers
}
getCaip2() {
return this.chainId
}
getChainId() {
return this.chainId
}
}
```
- Add test cases in `BitcoinChainAdapter.test.ts` and `EthereumChainAdapter.test.ts` to verify
- Constructor with no `chainId`
- …
> feat: refactor ChainAdapter.getCaip2() functions to be synchronous & add `getChainId` #381

- packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts
- move `const getGasFeesMockedResponse = {}` to a `makeGetGasFeesMockedResponse` function
- move `const estimateGasMockedResponse = {}` to a `makeEstimateGasMockedResponse` function
- move `const getInfoMockResponse = {}` to a `makeGetInfoMockResponse` function
- add a `makeGetAccountMockResponse` function instead of passing a new `getAccount` mock object every test, since only the balance/erc20 balance can change
- add a `makeChainAdapterArgs` function instead of mutating the `args` defined in `beforeEach`
> refactor(EthereumChainAdapter): use maker functions for tests

- packages/caip/src/caip19/caip19.test.ts
- packages/caip/src/caip19/caip19.ts
Currently `toCAIP2` throws an error if you pass in an `assetReference` of `slip44` for Cosmos/Osmosis. The correct CAIP19 for Cosmos is `cosmos:cosmoshub-4/slip44:118`. So if you call `toCAIP19(fromCAIP19(`cosmos:cosmoshub-4/slip44:118`))` it'll throw an error.
This PR fixes that.
> fix: support slip44 for Cosmos in toCAIP2

- README.md
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
This PR moves much of the BitcoinChainAdapter logic in a UTXOBaseAdapter class that can be re-used for future UTXO's.
It also includes some minor updates to the README
Have a few questions to run down before we merge and will add those as comments momentarily.
Currently, all existing tests pass, but have not done any additional testing past that. 
Closes #125
> feat: utxo chain adapter refactor

- packages/market-service/src/osmosis/osmosis.ts
- The api that is being used for Osmosis market does not have the ability to define a start/end date for price history data. This is a fix that returns the correct data points based on the time interval of each HistoryTimeFrame.
> fix: osmosis chart range data

- packages/chain-adapters/src/ChainAdapterManager.test.ts
- packages/chain-adapters/src/ChainAdapterManager.ts
we have a chainadaptermanager singleton in web and need to access it in and outside react. need the ability to remove chain adapters when we turn off feature flags. we can't replace the singleton, so we need to be able to remove individual chain adapters from the manager. this adds that functionality and unblocks broken feature flag functionality in web.
> feat: add remove function to chain adapters manager

- packages/chain-adapters/package.json
- packages/chain-adapters/src/ChainAdapterCLI.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/types/src/chain-adapters/cosmos.ts
- yarn.lock
- Add `signAndBroadcastTransaction` to cosmos and osmosis chain adapters
- Update `buildSendTransaction` to have dynamic `accountNumber` and `sequence` number
- Update chainAdapter CLI 
- closes #306
> feat: cosmos sign and broadcast tx

- packages/chain-adapters/package.json
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- yarn.lock
Currently, `CosmosSdkBaseAdapter` is using `WAValidator`, which doesn't support Cosmos.
This will produce some error if we try to validate some cosmos address:
```
wallet_address_validator.js:17 Uncaught (in promise) Error: Missing validator for currency: cosmos
at Object.validate (wallet_address_validator.js:17:1)
at ChainAdapter.validateAddress (CosmosSdkBaseAdapter.js:107:1)
```
This PR uses the V1Account endpoint, which has a middleware using the `IsValidAddress` function:
https://github.com/shapeshift/unchained/blob/1701f95c24a5e26edffa83f1e31da2f27a764778/go/pkg/cosmos/middleware.go#L19
By trying that request to `V1Account`, and catching on error status, we effectively have address validation implemented here, without needing to implement a whole new endpoint in unchained.
> fix(cosmos): actually validateAddress

- packages/types/src/chain-adapters/bitcoin.ts
This follows https://github.com/shapeshift/lib/pull/447 - we have a default Segwit Native `accountType`, so it shouldn't be required to explicitly pass it.
> fix: make accountType optional in BitcoinChainAdapter getAddress

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/types/src/chain-adapters/index.ts
See https://github.com/shapeshift/web/issues/651 - this adds support for memo field in `buildSendTransaction`, which is the method we use in web to build a send tx:
https://github.com/shapeshift/web/blob/1c6ba0e79e65d2c6b13c0f34cc1442b58a705d95/src/plugins/cosmos/components/modals/Send/hooks/useFormSend/useFormSend.tsx#L39-L45
Since tendermint/sig already supports creating a signed tx with memo (see https://tendermint.github.io/sig/interfaces/stdtx.html), we don't need any additional work in lib than this to support memos.
> feat: accept memo in buildSendTransaction

- packages/asset-service/src/generateAssetData/ethTokens/foxy.ts
Update icon url.  This was unable to be tested due to needing to be in main before github hosted it.
This is the correct url
> fix: foxy icon url

- package.json
- packages/asset-service/src/generateAssetData/ethTokens/yearnSdk.ts
- packages/caip/src/adapters/yearn/utils.ts
- packages/investor-yearn/src/api/api.ts
- packages/investor-yearn/src/api/yearn-sdk.ts
- packages/market-service/src/market-providers.ts
- packages/market-service/src/marketDataCLI.ts
`disableAllowList` was removed from the `Yearn()` constructor and is now defaulted - see upstream issue here https://github.com/yearn/yearn-sdk/issues/242
this fixes the build for CI.
> fix: fix yearn sdk instantiation

- packages/investor-foxy/src/api/api.ts
Strings were causing 'Invalid BigNumber string' error
> fix: don't use strings in contract calls

- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/api/foxy-types.ts
- packages/investor-foxy/src/foxycli.ts
this is required to unblock https://github.com/shapeshift/web/pull/1321
* **wip - @toshiSat to complete - handle stake events that trigger a rebase**
* include assetId in rebase history return type
* adjust the return type to be called blockTime in alignment with what web consumes
* adjust rebase balance diffs that are initiated by unstake events to exclude the transfer value
> fix: foxy rebase logic and types

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
This removes the console erroring at cosmos validation step, since web will produce an errored state, it currently produces log spew.
#487
> feat: don't log cosmos validation error

- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/api/foxy-types.ts
- packages/investor-foxy/src/constants/enums.ts
- packages/investor-foxy/src/foxycli.ts
- packages/types/src/base.ts
- Move `Withdrawal Type` to `types` package
- Add `WithdrawEstimateGasInput` for FOXy
NOTE: This PR is a prerequisite for merging of [foxy-withdrawals](https://github.com/shapeshift/web/pull/1330) in web.
> feat: move withdraw type to types package

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/types/src/chain-adapters/cosmos.ts
This adds `tokens` to the Validator type in Cosmos.
It is the amount of delegated tokens for that validator (including self-delegation) and will be used for TVL calculation in https://github.com/shapeshift/web/issues/1402.
> feat: add tokens to returned Validator type

- packages/errors/README.md
- packages/errors/package.json
- packages/errors/src/ErrorWithCause.test.ts
- packages/errors/src/ErrorWithCause.ts
- packages/errors/src/ErrorWithDetails.test.ts
- packages/errors/src/ErrorWithDetails.ts
- packages/errors/src/ForbiddenError.ts
- packages/errors/src/NotFoundError.ts
- packages/errors/src/RateLimitError.ts
- packages/errors/src/UnauthorizedError.ts
- packages/errors/src/ValidationError.ts
- packages/errors/src/createErrorClass.test.ts
- packages/errors/src/createErrorClass.ts
- packages/errors/src/errors.test.ts
- packages/errors/src/index.ts
- packages/errors/tsconfig.build.json
- packages/errors/tsconfig.json
- yarn.lock
This PR creates a new package called `errors`.
`errors` is designed to provide common named errors to make error handling more consistent. For example, in a plugin that talks to a backend API we shouldn't pass through the backend error directly. We should provide a named error and embed the backend error in the `cause` property.
For example:
```ts
try {
await axios.get('...')
} catch (e) {
if (e.statusCode === 429) {
throw new new RateLimitError('Rate limited', { cause: e })
}
```
We could change the errors to not accept a `message` but to create a default message. For example, `ValidationError` could take `{ details: { name: 'property', expected: 'a string', actual: 'null' } }` and generate a `message` of `Property ${name} is expected to be ${expected} but received ${actual}`.
> feat(errors): add new "errors" package

- packages/errors/README.md
- packages/errors/package.json
- packages/errors/src/ErrorWithDetails.test.ts
- packages/errors/src/ErrorWithDetails.ts
- packages/errors/src/createErrorClass.test.ts
- packages/errors/src/createErrorClass.ts
- packages/errors/src/errors.test.ts
- yarn.lock
This feature will allow us to support translations for error messages.
* The `code` property of an error should be a short string that could be used to lookup a translation for what error message should be shown to a user.
* Error codes are normalized to be UPPER_CASE+SNAKE_CASE so we can have some consistency. For example, `ERR_RATE_LIMIT`.
* All errors have a default code that matches the error's name.
> feat: add `code` to errors

- packages/swapper/package.json
- packages/swapper/src/api.ts
- packages/swapper/src/manager/SwapperManager.test.ts
- packages/swapper/src/manager/SwapperManager.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- Add filtering swapper buy/sell assets by assetId. This functionality is needed to filter trade-able assets when selecting assets to swap.
closes #538
> feat: swapper by buyasset

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.test.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
**NOTE: This is technically a breaking change, however, the methods being removed are not used anywhere in our codebase, so it is a "safer" breaking change.** 
- Remove `canTradePair` and `getAvailableAssets` from Swapper. 
- As a part of the Swapper refactor work, we have created methods that will replace these methods ([PR](https://github.com/shapeshift/lib/pull/526)) that improve on the naming and implementation. As we move away from using `ChainTypes` and move more to strictly using CAIP19s, removing these methods will bring us closer to that goal.
> chore: remove unused swapper methods

- packages/logger/README.md
- packages/logger/src/format.test.ts
- packages/logger/src/format.ts
- packages/logger/src/index.ts
- packages/logger/src/logger.test.ts
- packages/logger/src/logger.ts
- packages/logger/src/logger.type.ts
* feat(logger): support custom logging ouput function
* feat(logger): support formatting Errors with cause, details, and code
* chore(logger): update README to describe custom output logging functions and add some comments
You can now pass in `logFn` to the `Logger` constructor to provide a custom log output function. The function is provided with the log level and a `FormattedObject` of data.
> feat(logger): support custom logging output function

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
Including a zero-valued field here breaks with amino signers (like KK).
> fix(chain-adapters): don't set amount on MsgWithdrawDelegationReward

- packages/caip/src/caip10/caip10.ts
- packages/caip/src/caip19/caip19.ts
- packages/caip/src/caip2/caip2.ts
- packages/caip/src/index.ts
- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
Export types { AccountId, AssetId, ChainId } to replace { CAIP10, CAIP19, CAIP2 }
This is to be followed with a PR that removes { CAIP10, CAIP19, CAIP2 } once web PR [#1579](https://github.com/shapeshift/web/pull/1579) has been merged.
> refactor(caip): add accountid, assetid, chainid types

- packages/asset-service/package.json
- packages/chain-adapters/package.json
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/investor-foxy/package.json
- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/foxycli.ts
- packages/investor-yearn/package.json
- packages/market-service/src/market-service-manager.ts
- packages/swapper/package.json
This unbreaks the `yarn build` step, which is currently broken in latest develop since https://github.com/shapeshift/lib/commit/e02a2f4046e7a734f6e92d5ec448234a17818092:
- update `@shapeshiftoss/types` to latest where needed
- add missing `tokens` property in `transformValidator` return type
- narrow down the adapter type to be `ChainTypes.Ethereum` vs. `ChainTypes` currently in `investor-foxy`. This gives it a proper `T` generic type that's passed down to various methods and solves many type errors. This also gives it typing parity with `investor-yearn`, where the typing is actually the correct narrowed down one:
https://github.com/shapeshift/lib/blob/bf5aa33d3f3396ae652e618d3e1d5e4440711792/packages/investor-yearn/src/api/api.ts#L32 …
> fix: unbreak lib build

- packages/asset-service/src/generateAssetData/blacklist.json
we had two ETH assets - one was picking up the 0xeee burn address which we don't want to display in
the UI
> fix: blacklist 0xeee burn address

- packages/logger/src/logger.ts
- packages/logger/src/logger.type.ts
Errors from `try/catch` statements are `unknown`. The current types will require those caught errors to be cast.
There is no need or benefit to forcing the `Error` type because the logger formats parameters using type detection at runtime.
> chore(logger): change types for errors to unknown

- .github/workflows/pr.yml
- packages/caip/src/index.ts
- packages/chain-adapters/src/ChainAdapterCLI.ts
- packages/investor-foxy/src/api/api.ts
- tsconfig.build.json
- tsconfig.json
- Add `noUnusedLocals` TS rule.
- Fix existing code that breaks the rule
Note, this PR uses the name-spaced `caip2` import to match our existing, but incorrect convention - this better implementation is addressed separately in https://github.com/shapeshift/lib/pull/560.
N/A
N/A
N/A
N/A
> chore: add noUnusedLocals TS rule

- packages/types/package.json
- packages/types/src/base.ts
- packages/types/src/chain-adapters/index.ts
- packages/types/src/market.ts
**BREAKING CHANGE: caip-specific type properties have been renamed with their generic counterparts.**
This is a major version bump to the `@shapeshiftoss/types` package ~and uses semantic release notation~ - manually bumped the version as per https://github.com/shapeshift/lib/pull/560#issuecomment-1111182529.
Follow-on PRs will update all affected packages in `lib`, as well as `web` by handling the breaking change and bumping `@shapeshiftoss/types`.
Contributes to https://github.com/shapeshift/unchained/issues/398.
> chore(types): replace caip properties with their high-level counterparts

- packages/types/README.md
BREAKING CHANGE: trigger the major version bump that should have occurred with the changes in 3.1.4 in https://github.com/shapeshift/lib/pull/604.
Also fix the README header...
> chore(types): trigger major version bump attempt 2

- packages/types/README.md
BREAKING CHANGE: trigger the major version bump that should have occurred with the changes in 3.1.4 in https://github.com/shapeshift/lib/pull/604.
> perf(types): trigger major version bump

- packages/asset-service/src/generateAssetData/generateAssetData.ts
This:
- changes the sorting criteria for `filteredAssetData` from `caip19` to `assetId` to match the new high-level terminology we use. It will be needed for https://github.com/shapeshift/lib/pull/605 since it also regenerates asset data, but with the old criteria.
- regenerates `packages/asset-service/src/generateAssetData/generateAssetData.ts`.
> feat: regenerate asset data with assetId as sorting criteria

- packages/caip/src/caip19/caip19.ts
- packages/caip/src/caip2/caip2.ts
- packages/caip/src/utils.test.ts
- packages/caip/src/utils.ts
This moves the CAIP-related utils as well as related constants from web.
closes #557
This only moves utils that are strictly related to CAIPs.
If the input/output of such util is something from a domain-specific logic that's not *strictly* related to CAIPs (e.g account type, label, UTXO params etc...), it should not belong here and should stay defined where it is currently
> feat(caip): add caip-related utils/constants to caip package

- packages/asset-service/src/generateAssetData/ethTokens/ethereum.ts
- packages/asset-service/src/generateAssetData/ethTokens/foxy.ts
- packages/asset-service/src/generateAssetData/ethTokens/uniswap.ts
- packages/asset-service/src/generateAssetData/ethTokens/yearnVaults.ts
- packages/caip/src/index.ts
- packages/chain-adapters/src/ChainAdapterManager.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/foxycli.ts
- packages/market-service/src/coingecko/coingecko.ts
- packages/market-service/src/yearn/yearn-tokens.test.ts
- packages/market-service/src/yearn/yearn-tokens.ts
- packages/market-service/src/yearn/yearn-vaults.test.ts
- packages/market-service/src/yearn/yearn-vaults.ts
- packages/unchained-client/src/bitcoin/parser/index.ts
- packages/unchained-client/src/cosmos/parser/index.ts
- packages/unchained-client/src/ethereum/parser/index.ts
- packages/unchained-client/src/ethereum/parser/uniV2.ts
- packages/unchained-client/src/ethereum/parser/weth.ts
- yarn.lock
This flattens the caip exports instead of exporting each of the namespaces as their own module export. 
Following the release of this, https://github.com/shapeshift/web/pull/1591 should be merged, updating the usages.
- partially tackles #548
> feat(caip): flatten exports

- packages/caip/src/adapters/banxa/index.ts
this PR adds the map of converting our chains to the Banxa blockchain name.
web PR: https://github.com/shapeshift/web/pull/1478
this is where this function is used: https://github.com/shapeshift/web/pull/1478/files#diff-d11d8939921408eeb21dd7f5115e6b0ee21aeb464708b178b08c36ba5aecd12eR34
the input for this function is the selectedAssetTicker from Banxa list, this is the list:
https://github.com/shapeshift/lib/blob/b0dd979413f400db08bb360992148d49a4728478/packages/caip/src/adapters/banxa/index.ts#L4-L33
follow-up of: https://github.com/shapeshift/web/issues/1387
> feat(caip): banxa chain map

- packages/caip/README.md
- packages/caip/package.json
BREAKING CHANGE to major bump the caip package after https://github.com/shapeshift/lib/pull/625 did not.
> perf(caip): breaking readme change

- packages/caip/README.md
- packages/caip/package.json
BREAKING CHANGES: forcing a breaking change to major bump the caip package after https://github.com/shapeshift/lib/pull/625 did not.
> feat(caip): major bump commit

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/utils/index.ts
- packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
- packages/market-service/src/osmosis/osmosis.ts
- packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.ts
- packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.test.ts
- packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.ts
- packages/swapper/src/swappers/zrx/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/zrx/utils/helpers/helpers.ts
This removes the bn exports from chain-adapters utils.
The reason for that is that currently, they are available for consumers, which makes TypeScript Language Server confused and it will often pick the `@shapeshiftoss/` exports over the local ones in consumer(s) (which for now is just web, see https://github.com/shapeshift/web/pull/1760).
Other PRs will follow for `investor-foxy` and `investor-yearn` packages.
N/A
N/A, we just consume bn utils directly from `utils/bignumber` vs. re-exporting them in `utils` and consuming them from there
- Tests should still be happy
> chore(chain-adapters): do not export bn utils

- packages/errors/package.json
- packages/errors/tsconfig.build.json
- packages/errors/tsconfig.json
A recent change to the tsconfig files was made in every package except errors. This copies over all the configs from the 'logger' package.
> fix(errors): update tsconfigs to match other packages

- packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
Fixes issue: https://github.com/shapeshift/web/issues/1716
- Use standard fee as the normalization constant
- Use fast instead of instant (instant was often lower than slow for unknown reasons)
- Use the correct fee data for each return object (slow, average, fast)
There is a larger question/concern of relying on https://gas.api.0x.org/ for our fee calculations. Using the `MEDIAN` return value from this api results in a lower gas price than that returned by geth or something like https://etherchain.org/tools/gasnow. The result lines up more with https://ethgasstation.info/.
There are clearly fee discrepancies across the ecosystem depending on where you look, so we should have a discussion on whether we are ok with the returned data from 0x or if we want to build out the unchained fees …
> fix: correct fee calculation for eth/erc20 sends

- packages/market-service/src/exchange-rates-host/erhMockData.ts
- packages/market-service/src/exchange-rates-host/exchange-rates-host.test.ts
- packages/market-service/src/exchange-rates-host/exchange-rates-host.ts
the exchange rate host was returning newer fiat price history data first, we should be returning
oldest at the beginning of the array, like we do with crypto data.
also uses bnOrZero and deletes redundant NaN test as a result
> fix: sort fiat price history by time correctly

- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts
- packages/swapper/src/swappers/zrx/utils/test-data/setupZrxDeps.ts
getInfo is not part of the chain adapter interface and is not used anywhere.
We noticed this trying to implement osmosis and believe it should be removed
> chore: remove getinfo from cosmos base adapter

- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
Add fee asset id to chain adapters to make it easier to get the fee asset for a given asset
> chore: add get fee asset id to chain adapters

- packages/asset-service/package.json
- packages/chain-adapters/package.json
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/investor-foxy/package.json
- packages/investor-yearn/package.json
- packages/market-service/package.json
- packages/swapper/package.json
- packages/unchained-client/package.json
- packages/unchained-client/src/ethereum/parser/index.ts
- yarn.lock
- Update peer dependencies to breaking changes in https://github.com/shapeshift/lib/pull/656
- Remove 2 erroneous imports from `/src`
> chore: bump peer dependencies and remove src imports

- packages/market-service/src/exchange-rates-host/exchange-rates-host.test.ts
- packages/market-service/src/exchange-rates-host/exchange-rates-host.ts
the upstream API we use to fetch fiat pricing returns a max of 366 days per request - make multiple requests to return 5 years worth of data.
also only return 5 years as charts only go back that far
> fix: fetch multiple years for fiat price history

- packages/market-service/src/exchange-rates-host/exchange-rates-host.test.ts
- packages/market-service/src/exchange-rates-host/exchange-rates-host.ts
see the tests - we weren't returning any data for the hourly timeframe with the previous changes. ensures this works across all timeframes.
> fix: timeframes for fiat rates

- packages/chain-adapters/package.json
- packages/chain-adapters/src/ChainAdapterManager.test.ts
- packages/chain-adapters/src/ChainAdapterManager.ts
- yarn.lock
`ChainAdapter.getChainId()` was changed to a synchronous function a while back but the `byChainId` function was never updated to match.
`byChainId` was async for legacy reasons when we used to get the ChainId from the backend. We don't do that anymore and `byChain` was already changed to synchronous but `byChainId` didn't get changed at the same time.
This isn't a breaking change because you can `await` a synchronous function and you'll get back the correct result. This will only break cases where we use `.then` or `.catch` but I don't think we do.
> feat(chain-adapters): change byChainId to by synchronous

- packages/swapper/src/manager/SwapperManager.ts
- packages/swapper/src/swappercli.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- packages/swapper/src/swappers/zrx/utils/blacklist.ts
add blacklist and make getBestSwapper return possibly undefined
remove unused getSwapper()
> fix: add blacklist and make getBestSwapper return possibly undefined

- packages/types/src/market.ts
Due to previous PR changing 2 packages, creating this one containing only `types` changes from this PR : https://github.com/shapeshift/lib/pull/670
To be merged first.
> feat: add supply and maxSupply to marketData

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts
- packages/swapper/src/swappers/zrx/zrxExecuteTrade/zrxExecuteTrade.test.ts
- packages/swapper/src/swappers/zrx/zrxExecuteTrade/zrxExecuteTrade.ts
Add zrx specific trade type to hold zrx specific trade tx data.
This is safe to merge because web uses the `Trade` type and `ZrxTrade` extends `Trade`
> chore: add zrx specific trade type to hold zrx specific trade data

- packages/investor-foxy/README.md
- packages/investor-foxy/package.json
- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/foxycli.ts
- Updates `investor-foxy`'s CAIP package dependency to `5.0.0`, a breaking change: https://github.com/shapeshift/lib/pull/676
- Fixes variable naming of 'network' and 'chainId' - the values they contained were not these things
---
This is a patch release of `@shapeshiftoss/investor-foxy`.
> chore(investorFoxy): bump investor-foxy CAIP dependency to 5.0.0

- packages/market-service/package.json
- packages/market-service/src/coingecko/coingecko.ts
- packages/market-service/src/yearn/yearn-tokens.test.ts
- packages/market-service/src/yearn/yearn-tokens.ts
- packages/market-service/src/yearn/yearn-vaults.test.ts
- packages/market-service/src/yearn/yearn-vaults.ts
- yarn.lock
- Updates `market-service`'s CAIP package dependency to `5.0.0`, a breaking change: https://github.com/shapeshift/lib/pull/676
---
This is a patch release of `@shapeshiftoss/market-service`.
> chore(marketService): bump market-service CAIP dependency to 5.0.0

- packages/asset-service/package.json
- packages/asset-service/src/generateAssetData/ethTokens/ethereum.ts
- packages/asset-service/src/generateAssetData/ethTokens/foxy.ts
- packages/asset-service/src/generateAssetData/ethTokens/uniswap.ts
- packages/asset-service/src/generateAssetData/ethTokens/uniswapV2Pools.ts
- packages/asset-service/src/generateAssetData/ethTokens/yearnVaults.ts
- packages/asset-service/src/service/TrustWalletService.ts
- yarn.lock
- Updates `asset-service`'s CAIP package dependency to `5.0.0`, a breaking change: https://github.com/shapeshift/lib/pull/676
No asset re-generation should be necessary as this is a refactor only.
---
This is a patch release of `@shapeshiftoss/asset-service`.
> chore(assetService): bump asset-service CAIP dependency to 5.0.0

- packages/chain-adapters/package.json
- packages/chain-adapters/src/ChainAdapterManager.test.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- yarn.lock
- Updates `chain-adapters`' CAIP package dependency to `5.0.0`, a breaking change: https://github.com/shapeshift/lib/pull/676
---
This is a patch release of `@shapeshiftoss/chain-adapters`.
> chore(chainAdapters): bump chain-adapters CAIP dependency to 5.0.0

- packages/swapper/package.json
- packages/unchained-client/package.json
- yarn.lock
Bump `@shapeshiftoss/caip` to `5.0.0` in packages that are unaffected by the breaking change in https://github.com/shapeshift/lib/pull/676.
This is a patch release for the two affected package:
- `@shapeshiftoss/swapper`
- `@shapeshiftoss/unchained-client`
> chore: bump packages unaffected by CAIP 5.0.0 breaking change

- packages/caip/src/assetId/assetId.ts
A quick refactor to propagate the capture group pattern to remaining places in `caip`.
This is a patch release of `@shapeshiftoss/caip`
> refactor(caip): use regex capture groups

- packages/swapper/src/api.ts
- packages/swapper/src/manager/SwapperManager.test.ts
- packages/swapper/src/manager/SwapperManager.ts
- packages/swapper/src/swappercli.ts
- packages/swapper/src/swappers/test/TestSwapper.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxApprovalNeeded/ZrxApprovalNeeded.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.ts
- packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.ts
- packages/types/src/base.ts
- Replace usages of ExecQuoteOutput with TradeResult and remove ExecQuoteOutput
- Move swapper types from types package to swapper
This PR is only moving types around and does not have any functional changes. It is safe for web because web does not refernce any of the moved types
> chore: move types to swapper package & remove unused

- packages/swapper/src/api.ts
- packages/swapper/src/manager/SwapperManager.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
This adds a skeleton for CowSwapper interface implementation of  `Swapper` api with dummy methods.
Not much to test for the moment except that the few unit tests are green.
Related issue : https://github.com/shapeshift/lib/issues/721
> feat: implements cowswapper skeleton

- packages/types/package.json
- packages/types/src/base.ts
- Nomalizes `Asset` data
- Removes `BaseAsset` and `TokenAsset`, consolidated with `Asset`
This is the first of many PRs that will follow across `lib` packages and `web` to consume this change.
Contributes to https://github.com/shapeshift/lib/issues/711
This is an extract from the work started by @0xdef1cafe in https://github.com/shapeshift/lib/pull/712
This PR contains breaking changes to `@shapeshiftoss/types`.
> feat(types): remove Asset properties for normalization

- packages/chain-adapters/src/utils/utxoUtils.ts
Consumes the normalization of asset data and removal of unused properties.
Contributes to https://github.com/shapeshift/lib/issues/711
This is an extract from the work started by @0xdef1cafe in https://github.com/shapeshift/lib/pull/712
> feat(chainAdapters): consume normalization of Asset properties

- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
filter out thorchain assets for chains that the swapper does not yet support
> fix: filter out thorchain assets for chains that the swapper does not yet support

- packages/market-service/package.json
- packages/market-service/src/foxy/foxy.ts
- yarn.lock
We just instantiate the `EthereumChainAdapter` that we need
BREAKING CHANGE: Requires updated `peerDependencies`
> feat(market-service): removed usage of ChainAdapterManager

- packages/chain-adapters/src/api.ts
The `ChainAdapterManager` map type should actually have `ChainAdapter<ChainId>` type values.
> fix(chain-adapter): ChainAdapterManager type

- packages/asset-service/src/service/AssetService.ts
This follows https://github.com/shapeshift/lib/pull/746 and makes sure we build the right URL for the description of a native asset in `asset-service`.
The rationale for this change is `assetReference` can now either be the contract's address (in the case of an actual contract), or the native token's "real" asset reference.
This breaks the description generation as a link such as `https://api.coingecko.com/api/v3/coins/ethereum/contract/60` will be built to fetch description, which are invalid: in the case of a native token, it should simply be `https://api.coingecko.com/api/v3/coins/ethereum`.
Fixes Ethereum and BTC native tokens. Cosmos has hardcoded description, and thus isn't affected.
> fix(assetService): native asset description

- packages/asset-service/src/service/AssetService.ts
This fixes the build after 3baca79252326e3bb97b047bd53a6444dc03aea8, which builds fine in lib, but actually breaks web when installing `@shapeshiftoss/asset-service@latest`.
> fix(assetService): build fix

- packages/market-service/src/foxy/foxy.ts
- yarn.lock
We were already providing the ethereum URLs to the `MarketDataManager` so we just need to use those.
> fix(market-service): remove hard-coded chain adapter URLs

- packages/types/src/base.ts
`CoingeckoAssetPlatform` was going initially going to be introduced in https://github.com/shapeshift/lib/pull/794/files, but it's actually a shared type as it'll be used in both `asset-service` and `market-service`.
- https://github.com/shapeshift/lib/pull/799 to be updated once published
- https://github.com/shapeshift/lib/pull/793 to use the enum in tests, as per https://github.com/shapeshift/lib/pull/793#discussion_r895824260
> feat(types): add CoingeckoAssetPlatform enum

- packages/investor-foxy/package.json
- packages/investor-yearn/package.json
- packages/swapper/package.json
- yarn.lock
Fixes broken `main`. 
We were missing `unchained-client` as a dev dependency for `investor-foxy`, `investor-yearn`, and `swapper`.
> fix: add unchained-client devDependencies

- packages/caip/src/constants.ts
we need to add avalance c chain support to caip as a starting point, before we can consume this
throughout the stack
> feat: avalanche c chain support

- packages/caip/src/constants.ts
missed this on the previous PR into CAIP - adds avalanche c chain asset reference
> chore: add avalanche c chain asset reference

- docs/investor.md
This PR adds documentation on the `investor` single-sided staking abstraction.
This is intended to be used by implementers to understand what their implementation is expected to do and what data it's expected to return.
This draft is basically an explanation of the interfaces and does not provide a higher-level integration explanation.
closes #767
> docs: add documentation for the `investor` package

- packages/market-service/src/foxy/foxy.ts
- packages/market-service/src/foxy/foxyMockData.ts
This calls the `circulatingSupply` method from the FOXy contract to get the data for both the `foxyTotalSupply` and `supply` properties of the FOXy market data.
Currently, the `totalSupply` method from the contract is called for `foxyTotalSupply`, and `circulatingSupply` for `supply`.
https://github.com/shapeshift/web/issues/2024#issuecomment-1157086694
> So for FOXy the best way to get the actual totalSupply of tokens if the function [here](https://github.com/shapeshift/foxy/blob/f529540139865774384413433250e5e0ab01c99b/src/contracts/FOXy.sol#L187). This circulatingSupply is equivalent to the `Available Supply` as well.
Partially tackles https://github.com/shapeshift/web/issues/2024
> fix: consistently use Foxy.methods.circulatingSupply for supply

- packages/chain-adapters/src/ChainAdapterCLI.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/types.ts
This implements the signMessage method in `EthereumChainAdapter`. This is needed in order to be able to sign messages for `CowSwap` (will be used in https://github.com/shapeshift/lib/issues/726)
`ChainAdapterCLI` can be ran in order to verify signMessage is working.
> feat: chainadapters signMessage method

- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/cow/cowApprovalNeeded/cowApprovalNeeded.test.ts
- packages/swapper/src/swappers/cow/cowApprovalNeeded/cowApprovalNeeded.ts
- packages/swapper/src/swappers/cow/cowApproveInfinite/cowApproveInfinite.test.ts
- packages/swapper/src/swappers/cow/cowApproveInfinite/cowApproveInfinite.ts
- packages/swapper/src/swappers/thorchain/thorTradeApproveInfinite/thorTradeApproveInfinite.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.test.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- packages/swapper/src/swappers/zrx/zrxApprovalNeeded/zrxApprovalNeeded.test.ts
- packages/swapper/src/swappers/zrx/zrxApprovalNeeded/zrxApprovalNeeded.ts
- packages/swapper/src/swappers/zrx/zrxApproveInfinite/zrxApproveInfinite.test.ts
- packages/swapper/src/swappers/zrx/zrxApproveInfinite/zrxApproveInfinite.ts
- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.test.ts
- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts
Some non-standard naming conventions for file names and functions have been used, and are starting to propagate.
This PR ensures:
1. [lowerCamelCasing is used for functions](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#function_naming)
2. lowerCamelCasing is used for files exporting functions, or if the file exports a single class, the filename is exactly the name of the class
> fix(swapper): use best practice naming conventions

- packages/chain-adapters/src/evm/EVMBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
This adds a `rpcUrl` class property in `EVMBaseAdapter`, and a `getRpcUrl` getter.
Note that this hasn't been added to the other adapters, as the current need for getting the rpcUrl is to add an ethereum chain in https://github.com/shapeshift/hdwallet/pull/547 - if we do end up architecturally needing it in other adapters, we could add it there, but IMO it shouldn't be added just for the sake of consistency.
> feat(chain-adapters): add getRpcUrl to EVMBaseAdapter

- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
This bumps the gas limit for osmosis Txs to 300000/500000/700000
Relevant discussion: https://github.com/shapeshift/web/pull/2067#issuecomment-1175100530
> WRT failed Txs for unstake, I've noticed that 300000 seems to be the sweet gas spot that consistently broadcasts Txs.
We should adjust the gas for Osmosis Txs to be higher than what it is currently, as unstake Txs consistently fail. Note that the needed gas can very depending on current network conditions, so we should probably not rely on this number but rather use e.g 500000 as medium gas.
This should be updated in OsmosisChainAdapter's getFeeData.
> fix: bump osmosis gas limit

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
The `initialize()` method on a `Swapper` should be optional rather than no-opping it when it's not needed.
> feat(swapper): make initialize swapper method optional

- packages/swapper/src/manager/SwapperManager.ts
We don't actually want to deprecate `getSwapper` as we should continue to interact with the map via the `SwapperManager` helper abstractions.
Decided after removing in https://github.com/shapeshift/lib/pull/853, but then deduced that it didn't make sense to do so.
> chore(swapper): un-deprecate getSwapper

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/test/TestSwapper.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.test.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.test.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
- Since `swapperName` is not being used anywhere in lib or web, we will repurpose it to be used for Swapper's `tradeFeeSource` and anything else that would need a human readable swapper name.
**NOTE:** This is a breaking change, but nothing is currently using the code that is being changed.
> feat(swapper): repurpose 'swapperName' to be human readable name for each swapper

- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/utxo/UTXOBaseAdapter.ts
chain adapters should be the source of truth - this allows web to ask each chain adapter for a
display name to be used in the view layer, rather than maintaining a map of id -> name in the
consumer.
> feat: chain adapters getDisplayName

- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.ts
- The `filterBuyAssetsBySellAssetId` for ThorchainSwapper is currently checking to see if the `sellAsset` is supported. 
- This fixes that issue by checking if the sellAsset is a supported asset and if not, remove the ThorchainSwapper from the available swappers for that given sellAsset.
also a small copy change to update the error message of `getPriceRatio` to help with debugging.
> fix(swapper): fix filterBuyAssetsBySellAssetId for thorchain

- packages/chain-adapters/package.json
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- yarn.lock
Following https://github.com/shapeshift/web/pull/2165, we do disconnect nor switch to Mainnet on MM/XDEFI if the current chain isn't mainnet. Now that we have multiple EVM chains support, we actually do not need to be on any specific chain to show on-chain data, we only need to switch chains when calling `buildSendTransaction` if there is a mismatch between the adapter-expected EVM chainId and what the current's wallet EVM chainId is
> feat: switch EVM chains on buildSendTransaction

- packages/caip/src/utils.ts
Add Avalanche to the `chainIdToAssetId` mapping.
Supports https://github.com/shapeshift/web/issues/2156
Enables Avalanche accounts in `web`:
> feat(caip): add Avalanche mapping to chainIdToAssetId

- packages/chain-adapters/src/evm/index.ts
Exports `EvmChainIds` type for use in `web` to support EVM the work in https://github.com/shapeshift/web/pull/2164, allowing us to use tighter generics that are coupled with the `EvmBaseAdapter` types in `@shapeshiftoss/chain-adapters`.
[Example usage](https://github.com/shapeshift/web/blob/433824ea7438cb847243f8bac7bf90450bec73fd/src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx#L54):
```ts
const fees = estimatedFees[feeType] as FeeData<EvmChainIds>
```
Contributes to https://github.com/shapeshift/web/issues/2156.
> feat(chain-adapters): export `EvmChainIds` type

- packages/swapper/src/manager/SwapperManager.test.ts
- packages/swapper/src/manager/SwapperManager.ts
fix: silently fail if a swapper has already been added instead of throwing
We need this in order to cleanly handle async swapper initialization without having to catch every error if a swapper has already been added
> fix: silently fail if a swapper has already been added instead of throwing

- packages/swapper/src/manager/SwapperManager.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.test.ts
- packages/swapper/src/swappers/cow/cowGetTradeTxs/cowGetTradeTxs.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/utils/constants.ts
- packages/swapper/src/swappers/cow/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/cow/utils/helpers/helpers.ts
cowswap only supports erc20s, not ETH itself.
previously we were passing in a feeAsset to check for this case, and unnecessarily polluting the
interface and making the consumption of cowswapper messier.
given this is a swapper specific issue, and not going to change based on the fundamental design of
cowswap, and we already depend on the asset service, we can safely hardcode WETH in place of ETH
here to handle this specific case and expose a cleaner interface.
closes #844
- chore: don't require feeAsset in cow swapper dependencies
- test: fix cowswap tests to remove feeAsset
> chore: cowswap remove feeAsset

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/index.ts
- packages/swapper/src/swappers/utils/test-data/assets.ts
- packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.test.ts
- packages/swapper/src/swappers/zrx/getZrxMinMax/getZrxMinMax.ts
Add a type guard and check that buy and sell asset args for `getZrxMinMax` are both (a) on the same chain and (b) of type `EvmChainIds`.
Note, in a future PR I'd like to rename the new `EvmChainIds` type to the singular, `EvmChainId`.
Contributes to https://github.com/shapeshift/web/issues/2156
> feat(swapper): support all evm chains in `getZrxMinMax`

- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/api/foxy-types.ts
We don't want to ask for a `Contract` object as a parameter as we already have it inside `foxy-investor`. It still permits simplifying the usage of this method on web and any other projects using this dependency
It seems that we never used this method anywhere yet but we will need to use it in `web` https://github.com/shapeshift/web/pull/2225 as a safety
> refactor(investor-foxy): change contract param to contract address on canClaimWithdraw

- packages/caip/src/utils.test.ts
- packages/caip/src/utils.ts
This removes the `chainIdToFeeAssetId` function following https://github.com/shapeshift/web/pull/2159
- partially tackles https://github.com/shapeshift/lib/issues/875
> feat(caip): remove chainIdToFeeAssetId

- packages/market-service/src/exchange-rates-host/exchange-rates-host.ts
the upstream fiat exchange rate data source will return 0 for the current day for timezones with a
positive offset, e.g. australia
this filters out these invalid results
the client consuming this data will use the most recent rate rather than zero, fixing charts
> fix: don't return zero value fiat exchange rates

- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
- packages/swapper/src/swappers/cow/getCowSwapMinMax/getCowSwapMinMax.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- packages/swapper/src/swappers/cow/types.ts
- packages/swapper/src/swappers/cow/utils/constants.ts
- packages/swapper/src/swappers/cow/utils/helpers/helpers.test.ts
- packages/swapper/src/swappers/cow/utils/helpers/helpers.ts
This changes the endpoint used in `getUsdRate` method, because the one currently used has been deprecated.
I tested it in web, checked rates there and performed a swap.
closes https://github.com/shapeshift/lib/issues/759
Steps to test : 
- Link with web locally
- Start swap with ERC20 tokens (not ETH)
- Verify rates are consistent with current market
- Perform swap
> feat: replace '/api/v1/market' call with '/api/v1/quote' in getUsdRate

- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
This fixes an issue where user was still able to swap with an amount inferior to the minimum allowed amount for cowswap.
This issue was outlined by @gomesalexandre in this PR : https://github.com/shapeshift/lib/pull/916#pullrequestreview-1055963328
Steps to verify : 
- Launch web with local lib
- Try to perform a swap with a small amount > 0 for ERC-20 (not ETH)
- Notice the toast error, user is not able to proceed further in the swap
> fix: prevent user from cow swapping with small sell amount

- packages/caip/README.md
- packages/caip/src/adapters/coingecko/index.test.ts
- packages/caip/src/adapters/coingecko/index.ts
- packages/caip/src/adapters/coingecko/utils.ts
- packages/market-service/src/coingecko/coingecko.test.ts
- packages/market-service/src/coingecko/coingecko.ts
Stores an array of `AssetId`s, preventing the overwriting any existing `AssetId`s when there are multiple `AssetId`s mapping to a `CoinGeckoId`.
Before: `Record<CoinGeckoId, AssetId>`
After: `Record<CoinGeckoId, AssetId[]>`
With the `findAll` method fixed, when consumed by `web`  the assets page now shows all assets when Avalanche is enabled:
Contributes to https://github.com/shapeshift/web/issues/2101
> feat(caip & market-service): handle multiple assets with the same CoinGecko `id`

- packages/caip/tsconfig.json
Stops the IDE complaining about importing files not listed as part of the project, particularly in `packages/caip/src/adapters/coingecko/generated/index.ts`.
> chore(caip): add include & exclude patterns to caip's `tsconfig`

- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.ts
- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.test.ts
- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.ts
- packages/swapper/src/swappers/cow/getCowSwapMinMax/getCowSwapMinMax.test.ts
- packages/swapper/src/swappers/cow/getCowSwapMinMax/getCowSwapMinMax.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- packages/swapper/src/swappers/cow/utils/constants.ts
This enables `ETH` as a possible buy asset for swaps on CowSwap.
closes https://github.com/shapeshift/web/issues/2283
`0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` refers to the assetId used by `CowSwap` for `ETH` as buy asset.
Steps to test : 
- Launch web with local lib
- try to swap any ERC-20 to ETH
> fix: enables ETH as buy asset for CowSwap

- packages/caip/src/adapters/thortrading/index.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/thorchain/utils/constants.ts
- packages/swapper/src/swappers/thorchain/utils/estimateTradeFee/estimateTradeFee.test.ts
- packages/swapper/src/swappers/thorchain/utils/estimateTradeFee/estimateTradeFee.ts
- separate `buySupportedChainIds` from `sellSupportedChainIds` so we can easily add new buyAssets without having to implementing the sell logic at the same time.
- Add buy support for `doge` `ltc` `atom`
To test:
link locally. enable thorchain ff. enable litecoin ff. see that you can trade into ltc, doge & atom
> feat: additonal thorchain asset support

- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/thorchain/types.ts
- packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.ts
1) fix swaps into bch. Memos dont support `bitcoincash:` prefix.
2) fix detecting swaps into eth assets. Eth txids coming back from midgard dont have the 0x prefix and need it added
> fix: fix bch swaps and fix detecting swaps into eth assets

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
Makes Tx history great again after types refactor in https://github.com/shapeshift/lib/commit/944c8d12dc8380734fe197a8c7555c9c1ce903f7
Before:
After:
> fix(Transaction type): tradeDetails -> trade

- packages/swapper/src/swappers/cow/CowSwapper.ts
This exposes CowSwapper types for client-side consumption, since we need to consume the `feeAmountInSellToken` property which is specific to `CowTrade`.
Contributes to https://github.com/shapeshift/web/issues/2271
> feat(swapper): export CowSwapper types

- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/cow/utils.ts
Description
This adds an `isCowTrade` type guard, since we need to consume the feeAmountInSellToken property which is specific to CowTrade.
Issue
Contributes to https://github.com/shapeshift/web/issues/2271
> feat(swapper): add isCowTrade typeguard

- packages/unchained-client/src/evm/parser/zrx.ts
Use existing evm `Tx` type instead of custom union.
> chore(unchained-client): use evm tx type

- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.ts
This sets the CowSwap `tradeFee` to 0, and removes the related logic in that component which fetches the sell asset USD rate and calculating the USD fiat value.
According to our web consumption, the logic is wrong, and is not what `tradeFee` should refer to. In lib main currently, `tradeFee` in `cowBuildTrade` refers to `tradeFeeFiat` i.e the amount subtracted from the *sell* asset when swapping, *converted to fiat*
However, this is consumed by web as the amount subtracted from the *buy* asset (e.g native ETH fees) in *crypto*, see:
https://github.com/shapeshift/web/blob/7b9c730c5207659d35842b18dd0d26896a2df446/src/components/Trade/TradeConfirm/TradeConfirm.tsx#L248
Effectively, this means `tradeFee` should always be 0 for cow swaps, and the logic related to the making of this value …
> fix: always return 0 tradeFee for cow swaps

- packages/swapper/src/swappers/cow/cowGetTradeTxs/cowGetTradeTxs.test.ts
- packages/swapper/src/swappers/cow/cowGetTradeTxs/cowGetTradeTxs.ts
Fixes an issue where we are not passing a `sellTxid` to `web` for CowSwap trades when `cowGetTradeTxs()` is called, which is causing an exception and preventing the trade confirm screen from being shown once the transaction is complete.
Closes https://github.com/shapeshift/web/issues/2399
> feat(swapper): populate CowSwap `sellTxid`

- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/thorchain/utils/estimateTradeFee/estimateTradeFee.test.ts
- packages/swapper/src/swappers/thorchain/utils/estimateTradeFee/estimateTradeFee.ts
- packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.test.ts
- packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.ts
- packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.test.ts
`ThorSwapper`'s `getPriceRatio` is returning an inverted response, which is called when a `sellAmount` of `0` is quoted for.
We then invert it again here:
https://github.com/shapeshift/lib/blob/d3002a6ff2c5a220bf79aa8df08e03d581da2e32/packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts#L62
This hides the `getPriceRatio` bug when the `sellAmount` is `0`, e.g. for the initial quote, but then causes an inverted rate when `sellAmount` is _not_ `0`.
**Before** 😕 
**After** 😌 
Closes https://github.com/shapeshift/web/issues/2417
> fix(swapper): thorchainSwapper quote inversion

- packages/caip/src/adapters/banxa/index.ts
WIP - blocked upstream on banxa side - info at https://github.com/shapeshift/web/pull/2408
adds avax support to banxa caip mapping
closes #960
> feat: support avax via banxa

- packages/swapper/src/swappers/cow/cowApprovalNeeded/cowApprovalNeeded.ts
- packages/swapper/src/swappers/thorchain/thorTradeApprovalNeeded/thorTradeApprovalNeeded.ts
- packages/swapper/src/swappers/zrx/zrxApprovalNeeded/zrxApprovalNeeded.ts
This fixes the `approvalNeeded` methods that are currently checking for an allowance inclusive *lower than or equal* to the required allowance for a Tx, when they should check for exclusive *lower than* the required allowance for a Tx
Relates to the (closed) https://github.com/shapeshift/web/issues/2263 issue
> fix: off-by-one allowance check

- packages/swapper/src/api.ts
- packages/swapper/src/swappercli.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- packages/swapper/src/swappers/thorchain/buildThorTrade/buildThorTrade.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/thorchain/utils/bitcoin/utils/getThorTxData.ts
- packages/swapper/src/swappers/utils/test-data/setupSwapQuote.ts
Serialize `GetTradeQuoteInput` type args so we can use `getTradeQuote` with RTK query, which only supports serializable arguments.
A `HDWallet` object isn't actually needed.
This is a breaking change for `@shapeshiftoss/swapper`.
Follow-up `web` PR to support the breaking change: https://github.com/shapeshift/web/pull/2555
Contributes to https://github.com/shapeshift/web/issues/2556
> feat(swapper): serialize `GetTradeQuoteInput` type args

- packages/caip/src/accountId/accountId.test.ts
- packages/caip/src/adapters/coincap/index.test.ts
- packages/caip/src/adapters/coingecko/index.test.ts
- packages/caip/src/adapters/coingecko/index.ts
- packages/caip/src/assetId/assetId.test.ts
- packages/caip/src/chainId/chainId.test.ts
- packages/caip/src/constants.ts
- packages/caip/src/utils.test.ts
- packages/chain-adapters/src/utils/index.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/thorchain/buildThorTrade/buildThorTrade.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
BREAKING CHANGE: CHAIN_NAMESPACE.Bitcoin is now CHAIN_NAMESPACE.Utxo
This renames CHAIN_NAMESPACE.Bitcoin to CHAIN_NAMESPACE.Utxo since it
now refers to any UTXO chain
> feat: rename CHAIN_NAMESPACE.Bitcoin -> CHAIN_NAMESPACE.Utxo

- packages/caip/src/adapters/coincap/index.test.ts
- packages/caip/src/adapters/coingecko/index.test.ts
- packages/caip/src/adapters/coingecko/index.ts
- packages/caip/src/adapters/osmosis/index.test.ts
- packages/caip/src/adapters/osmosis/utils.ts
- packages/caip/src/assetId/assetId.test.ts
- packages/caip/src/chainId/chainId.test.ts
- packages/caip/src/constants.ts
- packages/chain-adapters/src/utils/index.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/thorchain/buildThorTrade/buildThorTrade.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
BREAKING CHANGE: CHAIN_NAMESPACE.Cosmos is now CHAIN_NAMESPACE.CosmosSdk
This renames CHAIN_NAMESPACE.Cosmos to CHAIN_NAMESPACE.CosmosSdk since it refers to any Cosmos SDK chain.
This brings consistency to the renamed 
- CHAIN_NAMESPACE.Bitcoin -> CHAIN_NAMESPACE.Utxo 
- CHAIN_NAMESPACE.Ethereum -> CHAIN_NAMESPACE.Evm
> feat: rename CHAIN_NAMESPACE.Cosmos -> CHAIN_NAMESPACE.CosmosSdk

- packages/caip/src/assetId/assetId.ts
- packages/caip/src/constants.ts
- packages/caip/src/typeGuards.ts
- packages/caip/src/utils.test.ts
- packages/caip/src/utils.ts
Non-breaking changes.
This removes the use of named capture groups in parseAssetIdRegExp to maintain compatibility with the Secure ECMAScript runtime.
> refactor(caip): remove named capture groups in parseAssetId regular expression

- packages/caip/src/constants.ts
We hardcode FOX and FOXy as strings throughout `web`, and sometimes use isolated constants for them.
This PR exports them from the CAIP package, giving us a stable source of truth for them moving forward.
Whilst these are the first non-fee EVM asset IDs to be exported, it feels reasonable as these assets in particular are frequently used in client-side code, and are likely to continue to be moving forward.
> feat(caip): add FOX & FOXy assetIds to constants

- packages/investor-yearn/src/YearnOpportunity.ts
- packages/investor-yearn/src/yearncli.ts
- packages/investor/package.json
- packages/investor/src/InvestorOpportunity.ts
- yarn.lock
BREAKING CHANGE: signAndBroadcast now accepts a bip44Params property in its input and will throw if not passed.
This PR:
- Accepts an optional (for backward-compatibility and not to break the abstracted `InvestorOpportunity` base type) `bip44Params` as input property
- Adds the optional property in the abstracted `InvestorOpportunity` 
- Tackles https://github.com/shapeshift/web/issues/2605
> feat(investor-yearn): accept bip44Params in signAndBroadcast input

- packages/investor-foxy/src/api/api.ts
- packages/investor-foxy/src/api/foxy-types.ts
- packages/investor-foxy/src/foxycli.ts
BREAKING CHANGE: investor-foxy now expects full `bip44Params` params in tx input methods instead of `accountNumber`
This PR:
- Replaces the previous`accountNumber` input field in investor-foxy methods with `bip44Params`
- Removes the making of `bip44Params` from `accountNumber`, since it's now passed in
- tackles https://github.com/shapeshift/web/issues/2611
- closes https://github.com/shapeshift/lib/issues/1000
> feat(investor-foxy): accept bip44Params

- .eslintrc
- .git-blame-ignore-revs
- packages/asset-service/src/generateAssetData/coingecko.ts
- packages/asset-service/src/generateAssetData/ethereum/overrides.ts
- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/coinselect.d.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/types.ts
- packages/chain-adapters/src/types.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- packages/chain-adapters/src/utxo/types.ts
- packages/investor/src/Investor.ts
- packages/swapper/src/api.ts
- packages/swapper/src/swappers/cow/types.ts
- packages/swapper/src/swappers/cow/utils/helpers/helpers.ts
- packages/swapper/src/swappers/utils/abi/erc20-abi.ts
- packages/swapper/src/swappers/zrx/types.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/foxyStaking.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/shapeShiftRouter.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/thor.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/uniV2.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/uniV2StakingRewards.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/weth.ts
- packages/unchained-client/src/evm/ethereum/parser/abi/yearnVault.ts
- packages/unchained-client/src/evm/parser/abi/erc20.ts
- packages/unchained-client/src/evm/parser/index.ts
- packages/unchained-client/src/types.ts
- packages/unchained-client/src/utils.ts
Adds `array-type` lint rule for codebase consistency.
https://typescript-eslint.io/rules/array-type/
> chore: add `array-type` lint rule

- packages/eslint-plugin-logger/package.json
This adds missing fields to the package.json of eslint-plugin-logger,
namely `{publishConfig: 'public'}` which will make sure the package gets
published as a public, scoped package.
> feat(eslint-pluggin-logger): add missing fields in package.json

- packages/unchained-client/generator/post_process.sh
- packages/unchained-client/package.json
The default parsing strategy for typescript-fetch is to use `.text()` for primitive response types. We have two unchained endpoints (`/gas/estimate` and `/send`) that currently return plain text responses. This resulted in a value `'"some string"'` being returned by the generated typescript client.
Using `json()` to parse these responses strips the quotes as desired and is the quick fix to prevent blocking lib/releases. Note, I have not tested against any other primitive type responses other than strings, but for our purposes at this time it works. Longer term fix would be to update the response payloads to be json across the board even if only returning a single string response and then we could remove the post processing to change parsing strategy.
> fix: use json response instead of text response for generated fetch api

- packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.test.ts
- packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.ts
- packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.ts
This fixes the rune swaps (from/to) following the mergefix of https://github.com/shapeshift/lib/commit/d6ae142598d82888d2c28190293ae56fc92c56e7 which ditched some logic from https://github.com/shapeshift/lib/pull/1030
- Link `@shapeshiftoss/swapper` with this diff in web with https://github.com/shapeshift/web/pull/2842 checked out
- RUNE swaps should be working on both sides
> fix: rune swaps

- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.test.ts
- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts
This PR fixes a bug where we'd always overwrite fee data for 0x trades.
`getAllowanceRequired` returns a `Promise<BigNumber>`.
A `BigNumber`, even when "0", is truthy.
`allowanceRequired`, therefore, is _always_ truthy.
The "conditional" code that always runs overwrites the fee data, every time.
Casting `as QuoteFeeData<T>` let this go unnoticed.
> fix: truthy check always true rugging 0x trade fee data

- packages/swapper/src/swappers/thorchain/buildThorTrade/buildThorTrade.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/thorchain/utils/txFeeHelpers/btcTxFees/getBtcTxFees.ts
The ThorChain swapper isn't doing anything with the `sendMax` argument being sent from the client.
This PR plumbs it through ThorSwap's `buildTrade` and `getTradeQuote`.
To test locally, link with https://github.com/shapeshift/web/pull/2955 and click "Max" on a UTXO asset - ensure we can get to the confirm trade screen without throwing.
Contributes to https://github.com/shapeshift/web/issues/2949, though requires the `web` PR to fully close: https://github.com/shapeshift/web/pull/2955
> fix(swapper): plumb `sendMax` through ThorSwapper

- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
we previously missed this and only native/keepkey support thor trades as they support offline
signing
this uses the signAndBroadcast method if it is available, e.g. metamask/xdefi/tally ho/walletconnect
> fix: allow thor trades for wallets that require signAndBroadcast

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/cow/CowSwapper.ts
- packages/swapper/src/swappers/osmosis/OsmosisSwapper.test.ts
- packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
- packages/swapper/src/swappers/test/TestSwapper.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.test.ts
- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/zrx/ZrxSwapper.ts
Use a `SwapperName` enum when referring to the swapper name.
Makes the `web` implementation for `https://github.com/shapeshift/web/issues/3019` tidier.
> chore(swapper): use and export a `SwapperName` enum

- packages/swapper/src/swappers/thorchain/constants.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
Closes https://github.com/shapeshift/web/issues/3024#event-7556633902
To test:
1. Link branch to `web`
2. Ensure ThorSwap enabled in `web`
3. Get ThorSwap quote for any trade into the Ethereum Mainnet - the minimum amount of the sell asset should be approximately equal to $50
> chore: set minimum ThorSwap sell amount to $50 on Ethereum Mainnet

- packages/chain-adapters/src/types.ts
- packages/investor-foxy/src/foxycli.ts
- packages/swapper/src/swappers/cow/cowApprovalNeeded/cowApprovalNeeded.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.ts
A subset of the type changes made in https://github.com/shapeshift/lib/pull/1054 to keep changes contained to the `chain-adapters` package and allow for a more manageable `web` migration.
The associated `web` PR: https://github.com/shapeshift/web/pull/3040 (note they can be merged independently).
This is a breaking change.
Contributes to https://github.com/shapeshift/lib/issues/1001
> feat(chain-adapters): make bip44Params required in `chain-adapters`

- packages/chain-adapters/src/types.ts
This is not a breaking change, as the methods corresponding to these types aren't used outside of `@shapeshiftoss/chain-adapters`.
Safe to merge independently of the other open PRs ✅
> feat(chain-adapter): enforce bip44Params on all remaining `chain-adapters` methods

- packages/investor-idle/package.json
- packages/investor-idle/src/IdleOpportunity.ts
- packages/investor-idle/src/idlecli.ts
- packages/investor-yearn/package.json
- packages/investor-yearn/src/YearnOpportunity.ts
- yarn.lock
Contributes to https://github.com/shapeshift/lib/issues/999.
Requires https://github.com/shapeshift/lib/pull/1061 to be merged, and an updated `@shapeshiftoss/investor` major version to be published (assumably `3.0.0`).
TODO once changes in https://github.com/shapeshift/lib/pull/1061 published:
```diff
--- a/packages/investor-yearn/package.json
+++ b/packages/investor-yearn/package.json
@@ -39,14 +39,14 @@
"@shapeshiftoss/caip": "^8.4.2",
"@shapeshiftoss/chain-adapters": "^10.0.0",
"@shapeshiftoss/hdwallet-core": "^1.35.0",
-    "@shapeshiftoss/investor": "^2.1.1",
+    "@shapeshiftoss/investor": "^3.0.0",
"@shapeshiftoss/types": "^8.3.1"
},
"devDependencies": {
"@shapeshiftoss/caip": "^8.4.2",
"@shapeshiftoss/chain-adapters": "^10.0.0",
"@shapeshiftoss/hdwallet-core": "^1.35.0",
- …
```
> chore: add `bip44Params` to investor children

- packages/swapper/src/swappers/cow/utils/blacklist.ts
- packages/swapper/src/swappers/zrx/utils/blacklist.ts
see comment in code - ERC20 rune is being deprecated and users should upgrade to native rune
we don't want people buying this asset by mistake
cannot buy
but are able to sell
> chore: blacklist erc20 rune from swapping

- packages/unchained-client/src/evm/ethereum/parser/__tests__/ethereum.test.ts
- packages/unchained-client/src/evm/ethereum/parser/uniV2.ts
Currently, there's an early return condition for UniV2 parser for Txs with confirmation.
This PR fixes it so that we parse all Txs and don't ditch the confirmed ones.
> fix: parse confirmed Txs with univ2 parser

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.ts
- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
- packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/thorchain/thorTradeApprovalNeeded/thorTradeApprovalNeeded.test.ts
- packages/swapper/src/swappers/thorchain/utils/cosmos/cosmosTxData.ts
- packages/swapper/src/swappers/thorchain/utils/txFeeHelpers/btcTxFees/getBtcTxFees.ts
- packages/swapper/src/swappers/thorchain/utils/txFeeHelpers/ethTxFees/getEthTxFees.ts
- packages/swapper/src/swappers/utils/test-data/setupSwapQuote.ts
- packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.test.ts
- packages/swapper/src/swappers/zrx/getZrxTradeQuote/getZrxTradeQuote.ts
- packages/swapper/src/swappers/zrx/utils/test-data/setupZrxSwapQuote.ts
- packages/swapper/src/swappers/zrx/zrxApprovalNeeded/zrxApprovalNeeded.test.ts
- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.test.ts
- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts
- packages/swapper/src/swappers/zrx/zrxExecuteTrade/zrxExecuteTrade.test.ts
BREAKING CHANGE: removes deprecated fields from QuoteFeeData.
Leaving in draft until a consuming `web` PR is ready.
> feat(swapper): remove deprecated QuoteFeeData fields

- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
- packages/swapper/src/swappers/thorchain/utils/getPriceRatio/getPriceRatio.ts
Fixes quote when sell asset is native RUNE and no amounts have been entered yet.
Closes https://github.com/shapeshift/web/issues/3066
**Before**
**After**
> fix(swapper): fix rune as sell asset

- packages/asset-service/package.json
- packages/caip/package.json
- packages/investor-yearn/package.json
- packages/market-service/package.json
- packages/market-service/src/yearn/yearnMockData.ts
- packages/unchained-client/package.json
- yarn.lock
- the recent upgrade of yearn sdk package has resulted in security access errors in web, downgrade to previous working version until it can be looked into further
> chore: downgrade yearnsdk to fix broken endpoints

- packages/unchained-client/src/evm/ethereum/parser/yearn.ts
try/catch yearn tx parsing so tx history loads
> fix: parse eth txs without yearn vaults

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- create shared `parsedTxToTransaction` function that both `subscribeTxs.onMessage` and `getTxHistory` can use
- metadata is now passed back in both cases resulting in correct transaction row display in the client
- may have also fixed trade confirmation display in trade modal as I am now seeing that update (although with polling it is not in sync with incoming buy side tx)
> fix: pass back metadata to onmessage handler

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- https://github.com/shapeshift/lib/pull/1081 inadvertently broke sends (apparently only on keepkey) by using the lib version of `chainId` instead of `chainReference` for the `chain_id` param on `txToSign`.
> fix: use chain reference as chain id

- packages/investor-idle/src/IdleOpportunity.ts
TVL parsing in investor-idle is wrong, confirmed the intent was to trim
the values to 6 significant digits (the decimal places of USDC the TVL
is denoted in), but this effectively parsed the numbers as way bigger
ones (e.g trillions instead of millions)
This PR removes the parsing and returns the raw numbers from Idle's API, so that web can
apply the parsing it needs.
> fix: return idle raw TVL values

- packages/market-service/package.json
- packages/market-service/src/idle/idle.ts
- packages/market-service/src/market-service-manager.ts
- yarn.lock
This PR:
- uses the right calculation to get the price of Idle opportunity tokens
- adds an `idle` market-service, getting Idle opportunity tokens' price and market cap
> feat(market-service): idle market service

- packages/swapper/src/swappers/thorchain/utils/getLimit/getLimit.ts
If we are sending a small amount to do a Thor trade, and the `outbound_fee` of the sell asset is high, it's possible that the refund fee is higher than the value of the trade.
In this case the limit should be 0 (but not negative), as in "finish this trade no matter what, as the amount is too small to refund it anyway".
The current logic, however, lets the memo limit go negative, which causes an error when executing the TX, e.g. https://live.blockcypher.com/btc/tx/60897031eec3714b079a8d5acb055e84f214bf037863fdcdd11d430c0ca71b5e/
> fix: add floor of 0 to limit

- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/thorchain/utils/constants.ts
- packages/swapper/src/swappers/thorchain/utils/txFeeHelpers/evmTxFees/getEvmTxFees.ts
Update some naming to make it clear that the values and functions are used for all EVMs, not just Ethereum.
Note, the hardcoded gas limit value still needs to be replaced (though it does work for Ethereum and Avalanche). 
I've reached out to 9R for more info on how best to do this.
> chore: use EVM-centric naming

- packages/market-service/src/idle/idle.ts
- packages/market-service/src/market-service-manager.ts
Actually reliable Idle market-service, since we don't have enough information from the API itself to get Idle tokens' prices, this uses Coingecko to get the underlying AssetId price, and multiplies it by the `pricePerShare` (the ratio of Idle token price / underlying token price)
> fix: idle market-service price

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getSlippage.test.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getSlippage.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
- packages/swapper/src/swappers/thorchain/utils/getLimit/getLimit.test.ts
- packages/swapper/src/swappers/thorchain/utils/getLimit/getLimit.ts
- packages/swapper/src/swappers/thorchain/utils/getTradeRate/getTradeRate.ts
- packages/swapper/src/swappers/thorchain/utils/test-data/responses.ts
- packages/swapper/src/swappers/utils/constants.ts
- packages/swapper/src/utils.ts
- Add `recommendedSlippage` as an optional property of `TradeQuote`. This will be consumed by `web` when fetching the quote and used to set the local state slippage value, which is then passed into `buildTrade`. This architecture allows us to override the `recommendedSlippage` with advanced trade settings in the future, as well as display the recommended slippage in the UI.
- Implemented `recommendedSlippage` for Thorswap. The logic handles the liquidity impact to pools when trading RUNE assets (one hop) and none-RUNE assets (two hops).
Contributes to https://github.com/shapeshift/lib/issues/1094
Unblocks https://github.com/shapeshift/web/pull/3419
> feat(swapper): add dynamic slippage

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/types.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.ts
- packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.ts
- packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.ts
- packages/swapper/src/api.ts
- packages/swapper/src/swappers/cow/CowSwapper.test.ts
- packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/utils/constants.ts
- packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
- packages/swapper/src/swappers/osmosis/utils/constants.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.test.ts
- packages/swapper/src/swappers/thorchain/getThorTradeQuote/getTradeQuote.ts
We use strings in places where we should be using enums, which can, and does lead to errors.
E.g. we are currently passing the string `thorchain` as the THORSwapper name, when it should be `THORChain`.
> chore: improve typing with enums

- packages/unchained-client/src/types.ts
Adds an `Osmosis` key to the `Dex` enum as part of some work to lift our TX URL handling logic in `web` to support conditional logic app wide, and fix https://github.com/shapeshift/web/issues/3446.
> chore: add Osmosis to Dex enum

- packages/asset-service/package.json
- yarn.lock
Internal bump of investor-idle including shapeshift/lib#1117, making auth great again for Idle API.
This PR ensures we can regenerate asset data for Idle.
> feat(asset-service): internal investor-idle bump

- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/types.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/types.ts
- packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.ts
- packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.ts
- packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.ts
Required for https://github.com/shapeshift/web/pull/2348
MetaMask is a smart fox. It detects that "Avalanche" (the name of the X chain) doesn't match the 43114 ChainId and throws some warnings when trying to programmatically add it in https://github.com/shapeshift/web/pull/2348
After renaming it to `Avalanche C-Chain`, this goes away and this is the only warning we're getting (WRT using our own JSON-RPC node):
> feat: rename Avalanche displayName -> Avalanche C-Chain

- packages/chain-adapters/src/api.ts
- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.ts
- packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.ts
- packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.ts
- packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.ts
Does what it says on the box - brings in the notion of a **non** display name for chain-adapters, to be used for e-g logging.
> feat(chain-adapters): adapter.getName()

- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
Fixes a regression in https://github.com/shapeshift/lib/pull/1122: https://github.com/shapeshift/lib/pull/1122/files#diff-19676c94d85c0baf6d1d359ea9be6657fb3a009be5536ea8c01bdba4d78ec2b6L103-L105.
The regression caused CoW Swap rates to be calculated incorrectly in `getCowSwapTradeQuote`.
Note, this regression is not yet in production - we haven't yet bumped swapper to the next major version in `web`.
Testing:
- Get a CoW Swap quote and confirm that the rate is correct.
Before: 
Fixed:
> fix(swapper): cowswap quote rate

- .github/workflows/pr.yml
- .github/workflows/release.yml
`actions/cache@v2` uses `save-state` and `set-output`, which have been deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR updates our workflows to use `actions/cache@v3`.
If this PR's CI build passes we should be gravy.
> feat: major bump `actions/cache`

- packages/investor-yearn/src/YearnOpportunity.ts
Does what it says on the box, for all intents and purposes, retired vaults are effectively *expired* in our web/lib abstraction.
We should treat them that way, so that they only show up in case a user is already deposited into it so they can withdraw.
- tackles https://github.com/shapeshift/web/issues/3529 - to be closed when consumed in web and a migration is ran there
See matching web PR https://github.com/shapeshift/web/pull/3556
> feat(investor-yearn): set retired vaults as expired

- packages/swapper/package.json
- packages/swapper/src/swappers/cow/utils/cowService.ts
- packages/swapper/src/swappers/thorchain/utils/thorService.ts
- packages/swapper/src/swappers/zrx/utils/zrxService.ts
- packages/swapper/src/swappers/zrx/zrxApprovalNeeded/zrxApprovalNeeded.test.ts
- packages/swapper/src/swappers/zrx/zrxApprove/zrxApprove.test.ts
- packages/swapper/src/utils.ts
- yarn.lock
- Adds caching to select swapper-related `GET` requests by including a cache adapter in 0x, THORSwapper, and CoW Swap services.
- Takes an opt-in approach to caching - we want to be explicit about what we cache, as some responses _must_ be current (order status)
- We use a max age of 5 seconds as a minimum bound for effectiveness, but not so large that we get stale data for crucial responses (e.g. THORSwapper inbound addresses)
- Reduces swapper-related requests by about 60%.
Contributes to https://github.com/shapeshift/web/issues/3466
> perf(swapper): add caching to swapper requests

- packages/swapper/src/swappers/thorchain/types.ts
- packages/swapper/src/swappers/thorchain/utils/test-data/responses.ts
Does what it says on the box - useful so we can either import this in web from swapper to type the response (probably not the best option since this is under the swapper umbrella), or at least ensure we have the most up-to-date schema to copy and paste it in web in case monkey see monkey do
> feat(swapper): update ThornodePoolResponse to the latest /lcd/thorchain/pools schema

- packages/investor-foxy/src/api/api.ts
- use `normalizeAmount` for `approve()` as `numberToHex()` will puke on scientific notation format string (`1e+22`)
> fix: normalize deposit amount for approval

- packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
- packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.test.ts
- packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.test.ts
- packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.test.ts
- packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.test.ts
defaulting to `index = 0` in `getBIP44Params` was a mistake - the `getAddress` function expects undefined as a valid input, which it uses to grab the next receive address. by explicitly passing 0, we were generating a valid address for index 0, but always index 0, because of `getBIP44Params` defaulting to 0 rather than undefined.
this is not an issue for evm or cosmossdk adapters, as while technically we can generate addresses with `index > 0`, this isn't a normal convention.
- fix: don't default index to 0 for utxo base adapter
- test: update tests to mock next address index correctly
> fix: utxo base adapter get address

- packages/swapper/src/swappers/osmosis/utils/helpers.ts
this was my mistake in a recent refactor - the Osmosis `account_number` that is returned from the `getAccount` call is *not* the same as the `accountNumber` that is used to construct `BIP44Params`
this PR reverts to using the correct `account_number` when building the trade tx, as per @elmutt @toshisat
> fix: use cosmos sdk account number in osmo buildTradeTx

- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.test.ts
- packages/swapper/src/swappers/cow/cowExecuteTrade/cowExecuteTrade.ts
Add multi-account support to CoW Swap.
To test, link locally and perform a swap on CoW Swap using an account > 0.
When confirming the trade the `POST` request to `https://api.cow.fi/mainnet/api/v1/orders/` should no longer error.
Successful trade on account 1: https://explorer.cow.fi/orders/0x2810939c88381c99c118a23344a9294c12595b9f3e3904925f1f77c43324a0db4f6b667cb7f5c55bb8f1155675d69a606b67ef0863bf974d
> feat(swapper): add multi-account support to CoW Swap

- packages/swapper/src/swappers/osmosis/utils/helpers.ts
- packages/swapper/src/swappers/osmosis/utils/osmoService.ts
* moves the osmosis swapper axios cache configuration to a separate file to match the pattern used in other swappers
* removes the trailing '/' from the osmoService cached URL so that calls to the `/gamm/v1beta1/pools` endpoint are cached properly
> fix(swapper): osmo swapper cached url, small refactor

- packages/chain-adapters/src/utxo/utxoSelect/index.test.ts
- packages/chain-adapters/src/utxo/utxoSelect/index.ts
If `input.from` is passed, the intent is to escape hatch the xpub privacy guarantees for destination addresses which business logic expect a single input address e.g THORSwap.
This PR makes sure we not only filter out UTXOs when `from` is passed, but also use it as a change address. This is effectively mimicking the behavior of wallets using a single *address* for UTXOs e.g THORSwap vs `wallets` using xpubs e.g us.
If the change address is automatically selected to be the next receive address, then this means either the `from` flow would work only once, or a Tx would have to be made to the previously used `from` address to populate an UTXO with the right value.
https://live.blockcypher.com/btc/tx/262848622bf782971dffa316dc755e9a2fac24555c4d847ce9356a889c0488f8/
> feat(utxoSelect): use `input.from` as change address if passed

- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.test.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.ts
- packages/chain-adapters/src/evm/types.ts
- packages/chain-adapters/src/types.ts
- packages/swapper/src/swappers/thorchain/utils/test-data/setupThorswapDeps.ts
- separate evm specific types from common chain adapter types
- add generic type for `ChainAdapterArgs` for explicit api type in concrete chain adapter
- update response payload for `estimateGas`
- re-refactor shared gas estimation logic to allow handling of l1 fees on optimism
- add l1 transaction fee to the existing l2 transaction fee for an accurate estimation of total transaction fees required for optimism tx
> feat: optimism l1 fees

- packages/asset-service/src/generateAssetData/osmosis/index.ts
- packages/asset-service/src/service/generatedAssetData.json
* fixes osmosis LP token generation
* regenerated `generatedAssetData.json`
* use `rawcdn.githack.com` urls instead of `raw.githubusercontent.com` urls for osmosis icons
* update osmosis icon urls every time assetdata is regenerated to avoid using stale image data cached by githack
* verified that the number of osmosis lp tokens previously generated (110) is similar to the number of pool tokens generated after this fix (118)
> fix(asset-service): generate osmosis lp asset data

- packages/market-service/src/market-service-manager.ts
- packages/unchained-client/package.json
- packages/unchained-client/src/evm/ethereum/parser/__tests__/ethereum.test.ts
- packages/unchained-client/src/evm/ethereum/parser/index.ts
- packages/unchained-client/src/evm/ethereum/parser/yearn.ts
Part of web spew cleaning - disabled Yearn in market-service and unchained-client.
See current grep for `yfi.sdk`.
- `market-service` is directly consumed in web, thus will reduce spew instantly
- `unchained-client`parsers are consumed in `chain-adapters` and will require an internal bump as a follow-up
- `caip` and `asset-service` usages are within a generate-once script kind of context, thus are not explicitly required to cleanup spew. Removing Yearn from there. Removing them from there would effectively mean Yearn assets wouldn't show up nor be able to be parsed as CAIPs anymore, removing the Yearn featureset fully, which is a product question. 
```shell
$ rg -l -g !**/node_modules** yfi.sdk
packages/market-service/src/marketDataCLI.ts …
```
> feat: disable Yearn in market-service / unchained-client

- packages/swapper/src/swappers/zrx/zrxApprove/zrxApprove.ts
- add type to local `approvalQuote` var to catch any future property name changes
- overwrite `sellAmountBeforeFeesCryptoBaseUnit` with correct `approvalAmount` value for approve infinite
> fix: use correct sell amount for approve infinite

- packages/market-service/src/osmosis/osmosis.test.ts
- packages/market-service/src/osmosis/osmosis.ts
* uses the URL module to safely construct osmosis market service URLs. This avoids potential errors with the base URL is passed in from web with/without a trailing slash.
> feat(market-service): safe URL construction with URL module

- packages/investor-foxy/package.json
- packages/investor-idle/package.json
- packages/investor-yearn/package.json
- packages/market-service/package.json
- packages/swapper/package.json
- yarn.lock
`@shapeshiftoss/chain-adapters` is out of date in `@shapeshiftoss/swapper`, causing CI to fail.
This PR bumps `@shapeshiftoss/chain-adapters` a major version to `11.0.0` for all packages.
> chore: bump @shapeshiftoss/chain-adapters dependencies

- packages/asset-service/src/generateAssetData/osmosis/index.ts
* corrects Osmosis LP asset precision (6->18)
* regenerated generatedAssetData.json
> fix(asset-service): osmosis lp token precision

- packages/market-service/src/osmosis/osmosis.ts
* fixes precision issue with Osmosis LP token price data
> fix(market-service): return correct osmosis lp asset price data

- packages/market-service/src/osmosis/osmosis.ts
* fixes precision on supply/maxSupply fields for Osmosis LP asset market data
> fix(market-service): use correct precision for osmosis lp assets

- packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/assertIsValidMemo.test.ts
- packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/assertIsValidMemo.ts
- packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/makeSwapMemo.ts
Assert that a memo is valid and throw if not - prevents invalid memos from ending up in THORSwap trades.
> feat(swapper): add memo assertion

- packages/swapper/src/swappers/thorchain/utils/getLimit/getLimit.test.ts
- packages/swapper/src/swappers/utils/constants.ts
Updates `DEFAULT_SLIPPAGE` (a.k.a the default slippage for trades we can't get a dynamic slippage for, and which don't have a user-passed slippage, which isn't implemented in the view layer yet) to 0.2%.
To be consumed in web when this is published, **after updating `DEFAULT_SLIPPAGE` there as well**.
> feat(swapper): update default slippage to .2%

- packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
Undoes https://github.com/shapeshift/lib/pull/1135 and enables Avalanche trading on THORSwapper.
Very important when testing:
1. Swaps into and out of Avalanche assets via THORSwapper succeed, and land in the expected account
2. Multi-account swaps (e.g. from account 2, into account 3 etc) work as expected for swaps with Avalanche assets (via THORSwappeR)
> feat: enable Avalanche on THORSwapper

- packages/swapper/src/api.ts
- packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
* fixes ATOM(account 0) -> OSMO(account 1) trades as reported by [TShifty](https://discord.com/channels/554694662431178782/1066088208905031681/1078117897060225124).
* note: there is probably a way to accomplish the same thing making better use of the type system than sticking an optional field onto the base trade types. I played around with this for a while, but ended up reverting to the naiive case for expediency. If you've got any suggestions, please let me know and I'll be happy to fix.
> fix(swapper): osmosis multi-account swaps

- packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
* uses correct account number for swaps from osmosis to cosmoshub
> fix(swapper): unrug osmo->atom cross-chain swaps

- packages/investor-idle/src/IdleOpportunity.ts
Does what it says on the box, exposing `strategy` so that web can consume it and populate Idle tags for @reallybeard consumption
> feat(investor-idle): expose IdleOpportunity strategy

- packages/chain-adapters/package.json
- packages/investor-foxy/package.json
- packages/investor-idle/package.json
- packages/investor-yearn/package.json
- packages/investor/package.json
- packages/market-service/package.json
- packages/swapper/package.json
- packages/unchained-client/package.json
- yarn.lock
- due to mismatched versions, there were bignumber warning being thrown in web when locally linked
> chore: upgrade bignumber.js to match web

- packages/swapper/src/swappers/thorchain/utils/makeSwapMemo/assertIsValidMemo.ts
Fixes swaps to RUNE - rugged by one character with the same assumption as before.
RUNE isn't a pool, it is the native asset of the THOR network
> feat(swapper): unrug THOR swaps to RUNE

- packages/asset-service/src/generateAssetData/avalanche/index.ts
- packages/asset-service/src/generateAssetData/optimism/index.ts
- `icon` field is required and in the case of missing icon, avalanche and optimism weren't generating identicons as placeholder
> chore: add identicon generation to avalanche and optimism

- packages/swapper/src/swappers/zrx/zrxBuildTrade/zrxBuildTrade.ts
Extracted a fix from https://github.com/shapeshift/lib/pull/1219 where we were dividing a value that was _already_ a percentage by 100.
Related discussion: https://discord.com/channels/554694662431178782/1080598617800319057/1080653281996574741
> fix(swapper): 0x slippage calculation

- packages/chain-adapters/package.json
- packages/investor-foxy/package.json
- packages/investor-idle/package.json
- packages/investor-yearn/package.json
- packages/investor/package.json
- packages/swapper/package.json
* Depends on https://github.com/shapeshift/hdwallet/pull/600
* Updates hdwallet dependencies 
* HDWallet-keepkey v1.46.0 contains a fix for the Osmosis IBC transfer command. That package is not directly included in this repo, but this will keep the hdwallet package numbers in sync.
> fix(common): osmosis keepkey swaps

- packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
- packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
- packages/chain-adapters/src/cosmossdk/osmosis/OsmosisChainAdapter.ts
- packages/chain-adapters/src/evm/EvmBaseAdapter.ts
- packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.ts
- packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.ts
- packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.ts
- packages/chain-adapters/src/evm/optimism/OptimismChainAdapter.ts
- packages/chain-adapters/src/utils/fees.ts
- packages/chain-adapters/src/utils/index.ts
- packages/swapper/src/swappers/osmosis/OsmosisSwapper.ts
- packages/swapper/src/swappers/osmosis/utils/helpers.ts
- single const
- use `MIN_FEE` in osmosis swapper
- use `MIN_FEE` with `calcFee` + `scalar` for `getFeeData`
> fix: update osmosis min fee to comply with v15.0.0 min consensus fee update

- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.test.ts
- packages/swapper/src/swappers/cow/getCowSwapTradeQuote/getCowSwapTradeQuote.ts
There is a logic error in the `getCowSwapTradeQuote` function. 
If we attempt to sell an amount that is less than the CoW Swap minimum, we get a quote using the minimum amount to ensure we still get a quote back.
The issue was that we are _always_ passing the buy asset amount that this minimum sell amount would buy (from the quote response) in the `buyAmountCryptoBaseUnit` field, regardless of if we made the minimum or not.
This is leading to inflated CoW Swap ratios which were rugging swapper selection UI, among a host of other bugs relating to minimum amounts.
To test this you'll need to be running https://github.com/shapeshift/web/pull/4177 on `web`, then:
1. Attempt to replicate the bug in https://github.com/shapeshift/web/issues/4168
2. With `REACT_APP_FEATURE_TRADE_RATES` enabled, …
> fix: cowswap buyAmountCryptoBaseUnit logic
